### ISSUE TITLE
Issue with android client

### ISSUE THREAD

**Issue by dested** [eclipsesource/tabris-js#1138]
I am getting this error in production. Unfortunately I dont know the circumstances of the crash as this is all google tells me. Let me know if I can provide any more information. 

I am on a nightly of 1.10

```
java.lang.RuntimeException: Unable to destroy activity {com.styr.app/com.eclipsesource.tabris.android.TabrisActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.eclipsesource.tabris.client.core.RemoteObject.getId()' on a null object reference
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3865)
    at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3883)
    at android.app.ActivityThread.-wrap5(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5461)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.eclipsesource.tabris.client.core.RemoteObject.getId()' on a null object reference
    at com.eclipsesource.tabris.android.internal.toolkit.operator.TabFolderOperator.destroyTabItems(TabFolderOperator.java:99)
    at com.eclipsesource.tabris.android.internal.toolkit.operator.TabFolderOperator.destroy(TabFolderOperator.java:84)
    at com.eclipsesource.tabris.android.internal.toolkit.AndroidWidgetToolkit.destroyObjects(AndroidWidgetToolkit.java:252)
    at com.eclipsesource.tabris.android.internal.toolkit.AndroidWidgetToolkit.dispose(AndroidWidgetToolkit.java:226)
    at com.eclipsesource.tabris.android.TabrisActivity.onDestroy(TabrisActivity.java:251)
    at android.app.Activity.performDestroy(Activity.java:6422)
    at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1143)
    at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3852)
```

**Comment by mpost** [comment]
I think this is related to https://github.com/eclipsesource/tabris-js/issues/713. We have included a workaround in the 1.x nightly builds on Android (it is already fixed in the 2.0.0-beta1). Please rebuild your app.
