### ISSUE TITLE
Android hard crash - v1.10.0

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#1207]
tabris android v1.10.1
only occurs when you go back to the root view. there is a drawer enabled for the app as well
there are several plugins loaded so it's probably one of them conflicting but any help in diagnosing the issue would be helpful. 

``` log
03-30 08:54:31.223: E/AndroidRuntime(4925): FATAL EXCEPTION: main
03-30 08:54:31.223: E/AndroidRuntime(4925): Process: com.sdlportal.sdlmobile3, PID: 4925
03-30 08:54:31.223: E/AndroidRuntime(4925): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/animation/AnimatorCompatHelper;
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.support.v7.widget.DefaultItemAnimator.resetAnimation(DefaultItemAnimator.java:514)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.support.v7.widget.DefaultItemAnimator.animateChange(DefaultItemAnimator.java:321)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.support.v7.widget.SimpleItemAnimator.animateChange(SimpleItemAnimator.java:149)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.support.v7.widget.RecyclerView.animateChange(RecyclerView.java:3510)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3320)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3080)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3518)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.View.layout(View.java:17637)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:614)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.View.layout(View.java:17637)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.View.layout(View.java:17637)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.View.layout(View.java:17637)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.View.layout(View.java:17637)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1079)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.View.layout(View.java:17637)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.View.layout(View.java:17637)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1192)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.View.layout(View.java:17637)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1192)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.View.layout(View.java:17637)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.View.layout(View.java:17637)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.View.layout(View.java:17637)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.View.layout(View.java:17637)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1741)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1585)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1494)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.View.layout(View.java:17637)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:726)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.View.layout(View.java:17637)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.ViewGroup.layout(ViewGroup.java:5575)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2346)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2068)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.Choreographer.doCallbacks(Choreographer.java:686)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.Choreographer.doFrame(Choreographer.java:621)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.os.Handler.handleCallback(Handler.java:751)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.os.Looper.loop(Looper.java:154)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at java.lang.reflect.Method.invoke(Native Method)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
03-30 08:54:31.223: E/AndroidRuntime(4925): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.animation.AnimatorCompatHelper" on path: DexPathList[[zip file "/data/app/com.sdlportal.sdlmobile3-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sdlportal.sdlmobile3-1/lib/arm, /system/fake-libs, /data/app/com.sdlportal.sdlmobile3-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
03-30 08:54:31.223: E/AndroidRuntime(4925): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by mpost** [comment]
Did you build the app in the last 2 weeks? Could be related to http://stackoverflow.com/questions/42987363/java-lang-noclassdeffounderror-failed-resolution-of-landroid-support-v4-animat

Is any of your plugins requesting the support library with w `*` wildcard?

**Comment by bFlood** [comment]
thanks for reply @mpost 

1. yes, this seemed to start about 2 weeks ago. I know I built a working android version last month and it did not have this issue. I will need to check if anything in the plugins changed but I have most of them pinned to specific version
2. this is using the Tabris Build servers but I wouldn't think those changed for v1.10.0 right?
3. wildcards - none that I could find but one had ```  <framework src="com.android.support:appcompat-v7:+" />``` that said, when I removed it from the build, the issue still occured

I'll keep looking and try the gradle changes recommended in those posts, thanks. if you can think of anything else or maybe confirm that the tabris build servers haven't changed

**Comment by mpost** [comment]
The build servers have most likely changes since we are building on travis and travis updates its support library version automatically. Therefore the new support library 26 alpha is available on travis and plugins that pull in support the library with an `*` version cause the problem as described in the SO post.

**Comment by mpost** [comment]
In fact we had some plugins that we were using in some apps that we needed to fork to pin the support library version to  the latest stable (`25.3.1`).

**Comment by bFlood** [comment]
thanks, its most likely the same issue then. I'll look for the plugin with the wildcard

1. can you list the plugins where you saw this issue? are they common ones like barcode scanner, camera etc?

2. what was the exact fix you used, just that gradle entry as described on the SO post?

**Comment by mpost** [comment]
The pinning was required in eg phonegap-plugin-barcode scanner.

When the plugin uses a separate gradle file your provide: `compile 'com.android.support:support-v4:25.3.0'`. If the plugin uses the `framework` element in the plugin.xml you provide `<framework src="com.android.support:support-v4:25.3.0" />`. Make sure to pin the version for all support library dependencies starting with `com.android.support`.

**Comment by bFlood** [comment]
can you give some more specific instructions, I'm getting build errors when trying to change these values:

if I remove this one line from the plugin.xml, it compiles but I get the same error as before at runtime
``` <framework src="com.android.support:appcompat-v7:25.3.0" />```

``` log
:processDebugManifest/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/AndroidManifest.xml:27:9-38 Error:
	Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38
	is also present at [com.android.support:appcompat-v7:25.3.0] AndroidManifest.xml:27:9-31 value=(25.3.0).
	Suggestion: add 'tools:replace="android:value"' to  element at AndroidManifest.xml:25:5-27:41 to override.
See http://g.co/androidstudio/manifest-merger for more information about the manifest merger.
:processDebugManifest FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38
  	is also present at [com.android.support:appcompat-v7:25.3.0] AndroidManifest.xml:27:9-31 value=(25.3.0).
  	Suggestion: add 'tools:replace="android:value"' to  element at AndroidManifest.xml:25:5-27:41 to override.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 1 mins 51.503 secs
Error: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/AndroidManifest.xml:27:9-38 Error:
	Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38
	is also present at [com.android.support:appcompat-v7:25.3.0] AndroidManifest.xml:27:9-31 value=(25.3.0).
	Suggestion: add 'tools:replace="android:value"' to  element at AndroidManifest.xml:25:5-27:41 to override.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38
  	is also present at [com.android.support:appcompat-v7:25.3.0] AndroidManifest.xml:27:9-31 value=(25.3.0).
  	Suggestion: add 'tools:replace="android:value"' to  element at AndroidManifest.xml:25:5-27:41 to override.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Warning: Command failed: cordova build --device --buildConfig=tabrisBuildConfig.json
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/AndroidManifest.xml:27:9-38 Error:
	Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38
	is also present at [com.android.support:appcompat-v7:25.3.0] AndroidManifest.xml:27:9-31 value=(25.3.0).
	Suggestion: add 'tools:replace="android:value"' to  element at AndroidManifest.xml:25:5-27:41 to override.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38
  	is also present at [com.android.support:appcompat-v7:25.3.0] AndroidManifest.xml:27:9-31 value=(25.3.0).
  	Suggestion: add 'tools:replace="android:value"' to  element at AndroidManifest.xml:25:5-27:41 to override.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/AndroidManifest.xml:27:9-38 Error:
	Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38
	is also present at [com.android.support:appcompat-v7:25.3.0] AndroidManifest.xml:27:9-31 value=(25.3.0).
	Suggestion: add 'tools:replace="android:value"' to  element at AndroidManifest.xml:25:5-27:41 to override.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:support-v4:26.0.0-alpha1] AndroidManifest.xml:27:9-38
  	is also present at [com.android.support:appcompat-v7:25.3.0] AndroidManifest.xml:27:9-31 value=(25.3.0).
  	Suggestion: add 'tools:replace="android:value"' to  element at AndroidManifest.xml:25:5-27:41 to override.
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
 Use --force to continue.
Aborted due to warnings.
travis_time:end:010965f6:start=1490991995540298756,finish=1490992149606276912,duration=154065978156

The command "grunt build deploy" exited with 6.
```

**Comment by mpost** [comment]
@bFlood Have you gone through all your plugins and checked there plugin.xml files and potentially other referenced .gradle files to check for wildcard support library inclusions?

**Comment by bFlood** [comment]
yes but I will look again. 

why would I get the compile error above though?

**Comment by mpost** [comment]
We have updated the cordova-android tabris platform to enforce a specific support library version (currently `25.3.1`). Could you try again with the latest 2.x nightly?

**Comment by mpost** [comment]
Btw... To enforce a version of a library you can put the following statement in the `cordova-android/bin/templates/project/build.gradle` file of your cordova android platform:

```groovy
configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support') {
            if (!requested.name.startsWith("multidex")) {
                details.useVersion '25.3.1'
            }
        }
    }
}
```

**Comment by bFlood** [comment]
I cannot build on 2.x, our apps are not ready yet (and to be honest, its going to be awhile before we can port them)

when building on the tabris servers, where would I place "configurations.all" statement above in our project? I can see where they go for plugins but for the main app, where do you define the gradle file (sorry if this is a basic question)

**Comment by mpost** [comment]
Can you build from 1.x nightlies? We could also add the pinning in 1.x.

**Comment by bFlood** [comment]
I'm building form 1.10.0, is there a 1.x nightly even available? (or is that the "nightly" one?)

if so, yes it would be great if you added this to 1.x as well

**Comment by mpost** [comment]
yeah it `nightly`. We need to rename that at some point

**Comment by bFlood** [comment]
does "nightly" have the pinning now? or does it need to be added?

**Comment by mpost** [comment]
give me a sec.

**Comment by mpost** [comment]
@bFlood We have now pinned the support library version in the tabris 1.x `nightly? builds to `25.3.1` as well.

**Comment by bFlood** [comment]
thank you, building now on "nightly". I'll let you know asap

**Comment by bFlood** [comment]
compile error, any thoughts?

``` log
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'android'.
> failed to find target with hash string 'android-23' in: /usr/local/android-sdk
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 22.562 secs
Error: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'android'.
> failed to find target with hash string 'android-23' in: /usr/local/android-sdk
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Please install Android target: "android-23".
Hint: Open the SDK manager by running: /usr/local/android-sdk-24.0.2/tools/android
You will require:
1. "SDK Platform" for android-23
2. "Android SDK Platform-tools (latest)
3. "Android SDK Build-tools" (latest)
Warning: Command failed: cordova build --device --buildConfig=tabrisBuildConfig.json
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'android'.
> failed to find target with hash string 'android-23' in: /usr/local/android-sdk
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'android'.
> failed to find target with hash string 'android-23' in: /usr/local/android-sdk
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Please install Android target: "android-23".
Hint: Open the SDK manager by running: /usr/local/android-sdk-24.0.2/tools/android
You will require:
1. "SDK Platform" for android-23
2. "Android SDK Platform-tools (latest)
3. "Android SDK Build-tools" (latest)
 Use --force to continue.
Aborted due to warnings.
travis_time:end:1db7570f:start=1491404415417905874,finish=1491404483085879507,duration=67667973633

The command "grunt build deploy" exited with 6.
Done. Your build exited with 1.
```

**Comment by mpost** [comment]
Thanks for the info. We will look into this.

**Comment by dested** [comment]
@bFlood This is typically because you don't have android sdk version 23 installed.

**Comment by bFlood** [comment]
thanks @dested but its the tabris build server

**Comment by irbull** [comment]
@bFlood Can you try again now. As we move forward we will add a `1.x-nightly` to make this explicit, but for now `nightly` should pick up the configuration for 1.x (it wasn't doing this, but I think I have that fixed).

**Comment by bFlood** [comment]
sorry for the delay, different error this time:

``` log
:CordovaLib:processDebugResources/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/CordovaLib/build/intermediates/res/merged/debug/values-v24/values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
    
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/CordovaLib/build/intermediates/res/merged/debug/values-v24/values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
    
 FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':CordovaLib:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/local/android-sdk/build-tools/25.0.2/aapt'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 1 mins 37.003 secs
Error: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/gradlew: Command failed with exit code 1 Error output:
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/CordovaLib/build/intermediates/res/merged/debug/values-v24/values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
    
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/CordovaLib/build/intermediates/res/merged/debug/values-v24/values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
    
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':CordovaLib:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/local/android-sdk/build-tools/25.0.2/aapt'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Warning: Command failed: cordova build --device --buildConfig=tabrisBuildConfig.json
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/CordovaLib/build/intermediates/res/merged/debug/values-v24/values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
    
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/CordovaLib/build/intermediates/res/merged/debug/values-v24/values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
    
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':CordovaLib:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/local/android-sdk/build-tools/25.0.2/aapt'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/gradlew: Command failed with exit code 1 Error output:
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/CordovaLib/build/intermediates/res/merged/debug/values-v24/values-v24.xml:3: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
    
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/CordovaLib/build/intermediates/res/merged/debug/values-v24/values-v24.xml:4: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
    
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':CordovaLib:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/local/android-sdk/build-tools/25.0.2/aapt'' finished with non-zero exit value 1
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
 Use --force to continue.
Aborted due to warnings.
travis_time:end:1ba748c0:start=1491491969342703053,finish=1491492116029246814,duration=146686543761

The command "grunt build deploy" exited with 6.
Done. Your build exited with 1.
```

**Comment by mpost** [comment]
@bFlood Sorry for the inconvenience. We have solved the issue. Please rebuild your app.

**Comment by bFlood** [comment]
thanks @mpost , new error:

``` log
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'android'.
> failed to find target with hash string 'android-25' in: /usr/local/android-sdk
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 24.691 secs
Error: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'android'.
> failed to find target with hash string 'android-25' in: /usr/local/android-sdk
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Please install Android target: "android-25".
Hint: Open the SDK manager by running: /usr/local/android-sdk-24.0.2/tools/android
You will require:
1. "SDK Platform" for android-25
2. "Android SDK Platform-tools (latest)
3. "Android SDK Build-tools" (latest)
Warning: Command failed: cordova build --device --buildConfig=tabrisBuildConfig.json
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'android'.
> failed to find target with hash string 'android-25' in: /usr/local/android-sdk
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Error: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring root project 'android'.
> failed to find target with hash string 'android-25' in: /usr/local/android-sdk
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Please install Android target: "android-25".
Hint: Open the SDK manager by running: /usr/local/android-sdk-24.0.2/tools/android
You will require:
1. "SDK Platform" for android-25
2. "Android SDK Platform-tools (latest)
3. "Android SDK Build-tools" (latest)
 Use --force to continue.
Aborted due to warnings.
travis_time:end:05c24228:start=1491571689023594437,finish=1491571762966809643,duration=73943215206

The command "grunt build deploy" exited with 6.
Done. Your build exited with 1.
```

**Comment by mpost** [comment]
Sorry about all the iterations. Please try again.

**Comment by bFlood** [comment]
success! everything is working as expected now, thank you very much for the fix
