### ISSUE TITLE
Latest Nightly gives cordova.js error...

### ISSUE THREAD

**Issue by jeffmikels** [eclipsesource/tabris-js#1234]
Error Loading cordova.js

1550 TypeError tabris.load is not a function.

**Comment by ralfstx** [comment]
Could you provide some more information? Which versions of Tabris.js and which client do you use? Is it a built app or do you load the source code via HTTP?

**Comment by jeffmikels** [comment]
How to reproduce the problem:

- Create Directory and `cd` into it.
- Initialize tabris with `tabris init` (Answer questions)
- edit tabris dependency in `package.json` to read `"tabris": "nightly"`
- run `tabris build android`
- run `adb install [apk_path]`

When the application runs on the device, the UI loads, but a toast pops up claiming tabris.load is not a function.

The ADB logcat is here:

```logcat
04-12 09:18:31.392  3954  3954 D SystemServicesProxy: getRecentTasks: com.eclipsesource.tabrisjs2
04-12 09:18:31.392  3954  3954 D SystemServicesProxy: getRecentTasks: com.eclipsesource.tabrisrss
04-12 09:18:41.177  3954  3954 D SystemServicesProxy: getRecentTasks: com.eclipsesource.tabrisjs2
04-12 09:18:41.177  3954  3954 D SystemServicesProxy: getRecentTasks: com.eclipsesource.tabrisrss
04-12 09:18:41.347  3036  4303 I ActivityManager: START u0 {cmp=org.jeffmikels.helloworld/com.eclipsesource.tabris.android.TabrisActivity (has extras)} from uid 10350 pid 25846 on display 0
04-12 09:18:41.497  3954  3954 D SystemServicesProxy: getRecentTasks: com.eclipsesource.tabrisjs2
04-12 09:18:41.497  3954  3954 D SystemServicesProxy: getRecentTasks: com.eclipsesource.tabrisrss
04-12 09:18:41.887 25846 25846 D incoming-operation: 'Get' on 'tabris.App' (tabris.App) with property 'tabrisJsVersion'
04-12 09:18:41.953 25846 25846 D incoming-operation: 'Create' on 'tabris.App' (tabris.App) with properties {}
04-12 09:18:41.954 25846 25846 W System.err: 	at com.eclipsesource.tabris.client.core.util.ParamCheck.throwException(ParamCheck.java:52)
04-12 09:18:41.954 25846 25846 W System.err: 	at com.eclipsesource.tabris.client.core.util.ParamCheck.notNull(ParamCheck.java:27)
04-12 09:18:41.954 25846 25846 W System.err: 	at com.eclipsesource.tabris.client.core.ObjectRegistry.register(ObjectRegistry.java:78)
04-12 09:18:41.954 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.TabrisOperationDelegate.create(TabrisOperationDelegate.java:32)
04-12 09:18:41.954 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.TabrisOperationDelegate.create(TabrisOperationDelegate.java:15)
04-12 09:18:41.954 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.OperationDispatcher.create(OperationDispatcher.java:34)
04-12 09:18:41.954 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.NativeBridge.create(NativeBridge.java:36)
04-12 09:18:41.954 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.V8JavaScriptBridge$6.invoke(V8JavaScriptBridge.java:153)
04-12 09:18:41.955 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.V8JavaScriptBridge.start(V8JavaScriptBridge.java:200)
04-12 09:18:41.955 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.JavaScriptBootStrategy.runJavaScript(JavaScriptBootStrategy.java:102)
04-12 09:18:41.955 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.JavaScriptBootStrategy.run(JavaScriptBootStrategy.java:62)
04-12 09:18:41.955 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.TabrisActivity.bootApp(TabrisActivity.java:115)
04-12 09:18:41.955 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.TabrisActivity.onCreate(TabrisActivity.java:73)
04-12 09:18:41.956 25846 25846 D incoming-operation: 'Create' on 'tabris.Ui' (o1) with properties {}
04-12 09:18:41.956 25846 25846 D incoming-operation: 'Create' on 'tabris.Composite' (o2) with properties {root=true, parent=o1}
04-12 09:18:41.959 25846 25846 D incoming-operation: 'Create' on 'tabris.StatusBar' (o3) with properties {parent=o1}
04-12 09:18:41.959 25846 25846 D incoming-operation: 'Create' on 'tabris.NavigationBar' (o4) with properties {parent=o1}
04-12 09:18:41.960 25846 25846 D incoming-operation: 'Create' on 'tabris.Drawer' (o5) with properties {parent=o1}
04-12 09:18:41.961 25846 25846 D incoming-operation: 'Create' on 'tabris.Device' (tabris.Device) with properties {}
04-12 09:18:41.961 25846 25846 W System.err: 	at com.eclipsesource.tabris.client.core.util.ParamCheck.throwException(ParamCheck.java:52)
04-12 09:18:41.961 25846 25846 W System.err: 	at com.eclipsesource.tabris.client.core.util.ParamCheck.notNull(ParamCheck.java:27)
04-12 09:18:41.961 25846 25846 W System.err: 	at com.eclipsesource.tabris.client.core.ObjectRegistry.register(ObjectRegistry.java:78)
04-12 09:18:41.961 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.TabrisOperationDelegate.create(TabrisOperationDelegate.java:32)
04-12 09:18:41.961 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.TabrisOperationDelegate.create(TabrisOperationDelegate.java:15)
04-12 09:18:41.962 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.OperationDispatcher.create(OperationDispatcher.java:34)
04-12 09:18:41.962 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.NativeBridge.create(NativeBridge.java:36)
04-12 09:18:41.962 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.V8JavaScriptBridge$6.invoke(V8JavaScriptBridge.java:153)
04-12 09:18:41.962 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.V8JavaScriptBridge.start(V8JavaScriptBridge.java:200)
04-12 09:18:41.962 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.JavaScriptBootStrategy.runJavaScript(JavaScriptBootStrategy.java:102)
04-12 09:18:41.962 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.JavaScriptBootStrategy.run(JavaScriptBootStrategy.java:62)
04-12 09:18:41.962 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.TabrisActivity.bootApp(TabrisActivity.java:115)
04-12 09:18:41.962 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.TabrisActivity.onCreate(TabrisActivity.java:73)
04-12 09:18:41.963 25846 25846 D incoming-operation: 'Get' on 'tabris.Device' (tabris.Device) with property 'scaleFactor'
04-12 09:18:41.966 25846 25846 D incoming-operation: 'Create' on 'tabris.ClientStore' (tabris.ClientStore) with properties {}
04-12 09:18:41.967 25846 25846 W System.err: 	at com.eclipsesource.tabris.client.core.util.ParamCheck.throwException(ParamCheck.java:52)
04-12 09:18:41.967 25846 25846 W System.err: 	at com.eclipsesource.tabris.client.core.util.ParamCheck.notNull(ParamCheck.java:27)
04-12 09:18:41.967 25846 25846 W System.err: 	at com.eclipsesource.tabris.client.core.ObjectRegistry.register(ObjectRegistry.java:78)
04-12 09:18:41.967 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.TabrisOperationDelegate.create(TabrisOperationDelegate.java:32)
04-12 09:18:41.967 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.TabrisOperationDelegate.create(TabrisOperationDelegate.java:15)
04-12 09:18:41.967 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.OperationDispatcher.create(OperationDispatcher.java:34)
04-12 09:18:41.967 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.NativeBridge.create(NativeBridge.java:36)
04-12 09:18:41.967 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.V8JavaScriptBridge$6.invoke(V8JavaScriptBridge.java:153)
04-12 09:18:41.967 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.V8JavaScriptBridge.start(V8JavaScriptBridge.java:200)
04-12 09:18:41.967 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.JavaScriptBootStrategy.runJavaScript(JavaScriptBootStrategy.java:102)
04-12 09:18:41.967 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.internal.javascript.JavaScriptBootStrategy.run(JavaScriptBootStrategy.java:62)
04-12 09:18:41.967 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.TabrisActivity.bootApp(TabrisActivity.java:115)
04-12 09:18:41.967 25846 25846 W System.err: 	at com.eclipsesource.tabris.android.TabrisActivity.onCreate(TabrisActivity.java:73)
04-12 09:18:41.968 25846 25846 D incoming-operation: 'Get' on 'tabris.Device' (tabris.Device) with property 'platform'
04-12 09:18:41.975 25846 25846 D incoming-operation: 'Create' on 'tabris.Crypto' (o6) with properties {}
04-12 09:18:41.975 25846 25846 D incoming-operation: 'Create' on 'tabris.Timer' (o7) with properties {repeat=false, delay=5000}
04-12 09:18:41.976 25846 25846 D incoming-operation: 'Listen' on 'tabris.Timer' (o7) with event 'Run = true'
04-12 09:18:41.977 25846 25846 D incoming-operation: 'Call' on 'tabris.Timer' (o7) with method 'start' with properties {}
04-12 09:18:42.001 25846 25846 D incoming-operation: 'Create' on 'tabris.Button' (o8) with properties {text=Show message, parent=o2}
04-12 09:18:42.006 25846 25846 D incoming-operation: 'Create' on 'tabris.TextView' (o9) with properties {parent=o2, font=Properties [properties={style=normal, size=24, family=[], weight=normal}]}
04-12 09:18:42.008 25846 25846 D incoming-operation: 'Listen' on 'tabris.Button' (o8) with event 'select = true'
04-12 09:18:42.009 25846 25846 D incoming-operation: 'Set' on 'tabris.Button' (o8) with properties {layoutData=Properties [properties={centerX=0, top=100}]}
04-12 09:18:42.010 25846 25846 D incoming-operation: 'Set' on 'tabris.TextView' (o9) with properties {layoutData=Properties [properties={centerX=0, top=[o8, 50]}]}
04-12 09:18:42.287  3036  3137 I ActivityManager: Displayed org.jeffmikels.helloworld/com.eclipsesource.tabris.android.TabrisActivity: +903ms (total +11s111ms)
04-12 09:18:42.345  3036  5035 I WindowManager: Switching to real app window: Window{63170b4 u0 org.jeffmikels.helloworld/com.eclipsesource.tabris.android.TabrisActivity}
04-12 09:18:42.382  3036  4858 I WindowManager: Switching to real app window: Window{63170b4 u0 org.jeffmikels.helloworld/com.eclipsesource.tabris.android.TabrisActivity}
04-12 09:18:44.974  3036  3117 D Embryo_Uterus: rank:42, com.eclipsesource.tabrisrss, 1266756
04-12 09:18:44.974  3036  3117 D Embryo_Uterus: rank:54, com.eclipsesource.tabrisjs2, 24803195
04-12 09:18:47.056 25846 25846 D incoming-operation: 'Destroy' on 'tabris.Timer' (o7)
04-12 09:18:47.320 25846 25846 D incoming-operation: 'Set' on 'tabris.TextView' (o9) with properties {text=Tabris.js rocks!}
04-12 09:18:48.377 25846 25846 D incoming-operation: 'Set' on 'tabris.TextView' (o9) with properties {text=Tabris.js rocks!}
04-12 09:18:48.932 25846 25846 D incoming-operation: 'Set' on 'tabris.TextView' (o9) with properties {text=Tabris.js rocks!}
04-12 09:18:49.282 25846 25846 D incoming-operation: 'Set' on 'tabris.TextView' (o9) with properties {text=Tabris.js rocks!}
04-12 09:18:49.513 25846 25846 D incoming-operation: 'Set' on 'tabris.TextView' (o9) with properties {text=Tabris.js rocks!}
04-12 09:19:33.364  3036  3117 D Embryo_Uterus: rank:43, com.eclipsesource.tabrisrss, 1266756
04-12 09:19:33.364  3036  3117 D Embryo_Uterus: rank:55, com.eclipsesource.tabrisjs2, 24803195
```

**Comment by mpost** [comment]
Are you also using the latest nightly tabris-android platform? (download on the right side here: https://tabrisjs.com/download)

**Comment by mpost** [comment]
pro tipp: if you consume the [tabris-cli](https://github.com/eclipsesource/tabris-js-cli) from its git repo, we have also added support for `tabris run android` which deploys to your device directly (similar to `cordova run`)

**Comment by jeffmikels** [comment]
Using the nightly tabris-android solved the problem.
