### ISSUE TITLE
Interacting with CollectionView Crashes on Android 4.4.2

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#1339]
### Problem description
Interacting (scrolling or tapping an item) with the main `CollectionView` in the Bookstore example of the 2.0-RC1 Android app causes the app to crash.  Scrolling the Examples list in the developer app does not crash.  I am able to reproduce the crash in a release build of my own app and the exception is the same.  The same actions on Android 6.0.1 and 7.0 do not cause a crash.  Possibly the same as #1323

### Environment

- Device (name and OS version): Samsung Galaxy Tab 4; Android 4.4.2
- Tabris.js version: 2.0.2-20170505-1053 (latest from Play Store)

### Logcat

```plain
E/AndroidRuntime(  554): FATAL EXCEPTION: main
E/AndroidRuntime(  554): Process: com.eclipsesource.tabrisjs2, PID: 554
E/AndroidRuntime(  554): java.lang.IllegalArgumentException: called detach on an already detached child ViewHolder{43839c70 position=2 id=-1, oldPos=-1, pLpos:-1 scrap [attachedScrap] tmpDetached}
E/AndroidRuntime(  554): 	at android.support.v7.widget.RecyclerView$5.detachViewFromParent(RecyclerView.java:781)
E/AndroidRuntime(  554): 	at android.support.v7.widget.ChildHelper.detachViewFromParent(ChildHelper.java:284)
E/AndroidRuntime(  554): 	at android.support.v7.widget.RecyclerView$LayoutManager.detachViewInternal(RecyclerView.java:8066)
E/AndroidRuntime(  554): 	at android.support.v7.widget.RecyclerView$LayoutManager.detachViewAt(RecyclerView.java:8059)
E/AndroidRuntime(  554): 	at android.support.v7.widget.RecyclerView$LayoutManager.scrapOrRecycleView(RecyclerView.java:8464)
E/AndroidRuntime(  554): 	at android.support.v7.widget.RecyclerView$LayoutManager.detachAndScrapAttachedViews(RecyclerView.java:8447)
E/AndroidRuntime(  554): 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:563)
E/AndroidRuntime(  554): 	at android.support.v7.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
E/AndroidRuntime(  554): 	at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3583)
E/AndroidRuntime(  554): 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3312)
E/AndroidRuntime(  554): 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3844)
E/AndroidRuntime(  554): 	at android.view.View.layout(View.java:15594)
E/AndroidRuntime(  554): 	at android.view.ViewGroup.layout(ViewGroup.java:4867)
E/AndroidRuntime(  554): 	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:636)
E/AndroidRuntime(  554): 	at android.view.View.layout(View.java:15594)
E/AndroidRuntime(  554): 	at android.view.ViewGroup.layout(ViewGroup.java:4867)
E/AndroidRuntime(  554): 	at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1197)
E/AndroidRuntime(  554): 	at android.view.View.layout(View.java:15594)
E/AndroidRuntime(  554): 	at android.view.ViewGroup.layout(ViewGroup.java:4867)
E/AndroidRuntime(  554): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
E/AndroidRuntime(  554): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
E/AndroidRuntime(  554): 	at android.view.View.layout(View.java:15594)
E/AndroidRuntime(  554): 	at android.view.ViewGroup.layout(ViewGroup.java:4867)
E/AndroidRuntime(  554): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
E/AndroidRuntime(  554): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
E/AndroidRuntime(  554): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
E/AndroidRuntime(  554): 	at android.view.View.layout(View.java:15594)
E/AndroidRuntime(  554): 	at android.view.ViewGroup.layout(ViewGroup.java:4867)
E/AndroidRuntime(  554): 	at android.support.constraint.ConstraintLayout.onLayout(ConstraintLayout.java:1197)
E/AndroidRuntime(  554): 	at android.view.View.layout(View.java:15594)
E/AndroidRuntime(  554): 	at android.view.ViewGroup.layout(ViewGroup.java:4867)
E/AndroidRuntime(  554): 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
E/AndroidRuntime(  554): 	at com.eclipsesource.tabris.android.internal.toolkit.view.TabrisDrawerLayout.onLayout(TabrisDrawerLayout.java:185)
E/AndroidRuntime(  554): 	at android.view.View.layout(View.java:15594)
E/AndroidRuntime(  554): 	at android.view.ViewGroup.layout(ViewGroup.java:4867)
E/AndroidRuntime(  554): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
E/AndroidRuntime(  554): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
E/AndroidRuntime(  554): 	at android.view.View.layout(View.java:15594)
E/AndroidRuntime(  554): 	at android.view.ViewGroup.layout(ViewGroup.java:4867)
E/AndroidRuntime(  554): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
E/AndroidRuntime(  554): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
E/AndroidRuntime(  554): 	at android.view.View.layout(View.java:15594)
E/AndroidRuntime(  554): 	at android.view.ViewGroup.layout(ViewGroup.java:4867)
E/AndroidRuntime(  554): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
E/AndroidRuntime(  554): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
E/AndroidRuntime(  554): 	at android.view.View.layout(View.java:15594)
E/AndroidRuntime(  554): 	at android.view.ViewGroup.layout(ViewGroup.java:4867)
E/AndroidRuntime(  554): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
E/AndroidRuntime(  554): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
E/AndroidRuntime(  554): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
E/AndroidRuntime(  554): 	at android.view.View.layout(View.java:15594)
E/AndroidRuntime(  554): 	at android.view.ViewGroup.layout(ViewGroup.java:4867)
E/AndroidRuntime(  554): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
E/AndroidRuntime(  554): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
E/AndroidRuntime(  554): 	at android.view.View.layout(View.java:15594)
E/AndroidRuntime(  554): 	at android.view.ViewGroup.layout(ViewGroup.java:4867)
E/AndroidRuntime(  554): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2348)
E/AndroidRuntime(  554): 	at android.vie
```

**Comment by mpost** [comment]
@cookieguru we can reproduce the problem and will work on it.

**Comment by mpost** [comment]
We have fixed the crash. Unfortunately, this means that we had to disable `highlightOnTouch` for now when directly applied on a cell in a _CollectionView_. This applies to older Android versions prior to Android 6.

As a workaround you can place another Composite inside your cell and apply `highlightOnTouch` on it.

New Android version use a different mechanism (using the ripple effect) and work as expected.

**Comment by ishigo1987** [comment]
Or you can simulate the HighlightOnTouch like that(Android < 6)
 createCell: () =>{
                           let cell = new tabris.Composite({
                               background:"#fff"
                            }).on("tap", function(){this.background = "#e0e0e0";setTimeout(() =>{cell.background = "#fff";},75);});

**Comment by cookieguru** [comment]
@ishigo1987 Sorta... `highlightOnTouch` actually uses a ripple effect which begins at the point of touch rather than highlighting the whole object straightaway.

**Comment by ishigo1987** [comment]
I know but I noticed that on my android (5.1) the highlightOnTouch is similar to the code I wrote before

**Comment by mpost** [comment]
Closing as resolved. Please reopen if you experience any more issues.

**Comment by cookieguru** [comment]
@mpost Is it safe to say that the effect will be unavailable (without using the workaround) on <6 for the foreseeable future?
