### ISSUE TITLE
Issue building on android (fresh install)

### ISSUE THREAD

**Issue by troyamelotte** [eclipsesource/tabris-js#1359]
Created a fresh install via tabris init ect and I'm getting this guy when I run 'tabris build android'

```C:\Users\STYR-TROY\Desktop\styrapp\testtest\testeroni>tabris build android
exec [./] npm.cmd run --if-present build:android
exec [./] npm.cmd run --if-present build
create build folder build/cordova
exec [build/cordova/www] npm.cmd install --production
testeroni@0.1.0 C:\Users\STYR-TROY\Desktop\styrapp\testtest\testeroni\build\cordova\www
`-- tabris@2.0.0-rc1

exec [build/cordova] cordova.cmd platform add C:\tabris\android
Adding android project...
Running command: cmd "/s /c "C:\tabris\android\bin\create.bat C:\Users\STYR-TROY\Desktop\styrapp\testtest\testeroni\platforms\android io.cordova.hellocordova HelloCordova --cli""
module.js:472
    throw err;
    ^

Error: Cannot find module './AndroidStudio'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\tabris\android\bin\templates\cordova\lib\AndroidProject.js:24:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
Error: cmd: Command failed with exit code 1
C:\Users\STYR-TROY\AppData\Roaming\npm\node_modules\tabris-cli\src\build.js:86
    throw new Error(`The command ${cmd} exited with ${ps.status}`);
    ^

Error: The command cordova exited with 1
    at exec (C:\Users\STYR-TROY\AppData\Roaming\npm\node_modules\tabris-cli\src\build.js:86:11)
    at runCordovaPlatformAdd (C:\Users\STYR-TROY\AppData\Roaming\npm\node_modules\tabris-cli\src\build.js:58:3)
    at build (C:\Users\STYR-TROY\AppData\Roaming\npm\node_modules\tabris-cli\src\build.js:37:3)
    at Command.program.command.description.action.platform (C:\Users\STYR-TROY\AppData\Roaming\npm\node_modules\tabris-cli\src\build.js:12:23)
    at Command.listener (C:\Users\STYR-TROY\AppData\Roaming\npm\node_modules\tabris-cli\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:194:7)
    at Command.parseArgs (C:\Users\STYR-TROY\AppData\Roaming\npm\node_modules\tabris-cli\node_modules\commander\index.js:615:12)
    at Command.parse (C:\Users\STYR-TROY\AppData\Roaming\npm\node_modules\tabris-cli\node_modules\commander\index.js:458:21)
    at Object.<anonymous> (C:\Users\STYR-TROY\AppData\Roaming\npm\node_modules\tabris-cli\src\tabris.js:10:9)

C:\Users\STYR-TROY\Desktop\styrapp\testtest\testeroni>```

**Comment by mpost** [comment]
Do you have the Android-sdk installed and set your ANDROID_HOME env var?

**Comment by mpost** [comment]
Closing as resolved. Please reopen if you experience any more issues.
