### ISSUE TITLE
JSX requires layoutData properties

### ISSUE THREAD

**Issue by mpost** [eclipsesource/tabris-js#1432]
### Problem description

When using JSX without layoutData the generated code does not run. The following snippet should produce a valid app:

```js
tabris.ui.contentView.append(
  <composite />
);
```
Instead the following error is printed:

```shell
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Composite._create (./node_modules/tabris/tabris.js:32:15315)
    at Composite.Widget (./node_modules/tabris/tabris.js:32:39786)
    at new Composite (./node_modules/tabris/tabris.js:32:48939)
    at Object.createElement (./node_modules/tabris/tabris.js:32:64252)
    at ./dist/app.js:3:34
    at Module.get (<anonymous>:1:902)
    at Module.require (<anonymous>:1:1202)
    at d (<anonymous>:1:3570)
    at Object.tabris._start (<anonymous>:1:3764)
```

### Expected behavior

Show a running app with a composite similar to

```js
tabris.ui.contentView.append(
  new tabris.Composite();
);
```

### Environment

- Tabris.js version: 2.0.0

**Comment by tbuschto** [comment]
This should been fixed as of commit 127b2227a58a082da436dcc13096ee7fe339f277. Are you maybe using an outdated tabris.js module?

**Comment by mpost** [comment]
I was on `b423eb680c246056f2cb2f8eaf0292ff42af1021`

> [doc] Fix HTML in platform labels, add tooltip Ralf Sternberg 12.07.2017 16:03 

which would be after your mentioned commit.

**Comment by dalisoft** [comment]
@mpost I cant reproduce the issue as for me works best both original and fork tabris.js. there maybe some issues relaed to npm cache or something

**Comment by mpost** [comment]
I can confirm that with the latest tabris.js 2.0.0 the issue is resolved.
