### ISSUE TITLE
Console output for thrown errors is not helpful

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1485]
### Problem description

Since Tabris.js 2.1, output for thrown errors is hard to read on iOS. Error message and name are not printed anymore.

### Expected behavior

Console output for thrown errors should have the same formatting on all platforms.

### Environment

- Tabris.js version: 2.1
- OS: iOS 10

### Code snippet

```javascript
throw new Error('Hello!');
```

Console output:

* **iOS**
```
⊘ Could not load main module: { http://192.168.6.146:8080/console.js:1:78
get
value
n
subscribe@file:///var/containers/Bundle/Application/805388F0-4026-4B57-B896-5E9E3ADB5389/Tabris.js%202.app/www/cordova.js:713:16
addEventListener@file:///var/containers/Bundle/Application/805388F0-4026-4B57-B896-5E9E3ADB5389/Tabris.js%202.app/www/cordova.js:133:43
file:///var/containers/Bundle/Application/805388F0-4026-4B57-B896-5E9E3ADB5389/Tabris.js%202.app/www/cordova.js:1428:34
_start
  line: 1,
  column: 78,
  sourceURL: 'http://192.168.6.146:8080/console.js' }
```
* **Android (expected)**
```
Could not load main module: Error: Hello!
    at ./console.js:1:69
    at e.get (<anonymous>:1:2332)
    at e.value (<anonymous>:1:2590)
    at Channel.n (<anonymous>:1:3490)
    at Channel.fire (./cordova.js:820:23)
    at Object.fireDocumentEvent (./cordova.js:230:45)
    at ./cordova.js:1215:28
    at Channel.f (./cordova.js:692:33)
    at Channel.fire (./cordova.js:820:23)
    at Object.initializationComplete (./cordova.js:738:19)
```

**Comment by ralfstx** [comment]
That's caused by the new Console implementation. This implementation relies on the `err.stack` property to contain the error type and message. This is the case in V8, but apparently not in JavaScriptCore.
