### ISSUE TITLE
Android build fails: No more handles [gtk_init_check() failed]

### ISSUE THREAD

**Issue by gtmadev** [eclipsesource/tabris-js#1550]
Android build fails with:

Exception in thread "main" org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]

`Warning: Command failed: tabris build android  --debug --device --verbose --cordova-build-config="../../../tabrisBuildConfig.json"`

`Exception in thread "main" org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]`

Here is the full verbose error:

Warning: Command failed: tabris build android  --debug --device --verbose --cordova-build-config="../../../tabrisBuildConfig.json"
Exception in thread "main" org.eclipse.swt.SWTError: No more handles [gtk_init_check() failed]
	at org.eclipse.swt.SWT.error(Unknown Source)
	at org.eclipse.swt.widgets.Display.createDisplay(Unknown Source)
	at org.eclipse.swt.widgets.Display.create(Unknown Source)
	at org.eclipse.swt.graphics.Device.(Unknown Source)
	at org.eclipse.swt.widgets.Display.(Unknown Source)
	at org.eclipse.swt.widgets.Display.(Unknown Source)
	at org.eclipse.swt.widgets.Display.getDefault(Unknown Source)
	at org.eclipse.swt.widgets.Shell.(Unknown Source)
	at org.eclipse.swt.widgets.Shell.(Unknown Source)
	at com.android.sdkuilib.internal.repository.ui.SdkUpdaterWindowImpl2.createShell(SdkUpdaterWindowImpl2.java:168)
	at com.android.sdkuilib.internal.repository.ui.SdkUpdaterWindowImpl2.open(SdkUpdaterWindowImpl2.java:137)
	at com.android.sdkuilib.repository.SdkUpdaterWindow.open(SdkUpdaterWindow.java:111)
	at com.android.sdkmanager.Main.showSdkManagerWindow(Main.java:413)
	at com.android.sdkmanager.Main.doAction(Main.java:391)
	at com.android.sdkmanager.Main.run(Main.java:151)
	at com.android.sdkmanager.Main.main(Main.java:117)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gtmamobile@0.1.0 build: `android`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gtmamobile@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2017-11-18T16_17_24_258Z-debug.log
The command npm exited with 1

**Comment by gtmadev** [comment]
Update:

Looks like I formatted my build script wrong. Actually, there was no need to add a line for the build script. I removed that and the builds worked fine.
