### ISSUE TITLE
Stack trace length on Android limited to 10 lines

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#1766]
### Problem description

Any result of `new Error().stack` is limited to 10 lines.

### Expected behavior

Print entire stack trace (within reason).

### Environment

Any Android version of Tabris.js.

### Code snippet

```javascript

function a() { console.log(new Error().stack); }
function b() { a(); }
function c() { b(); }
function d() { c(); }
function e() { d(); }
function f() { e(); }
function g() { f(); }
function h() { g(); }
function i() { h(); }
function j() { i(); }
function k() { j(); }
function l() { k(); }
function m() { l(); }

m();
```

Result:
```
Error
    at a (./dist/imageview.js:16:28)
    at b (./dist/imageview.js:17:16)
    at c (./dist/imageview.js:18:16)
    at d (./dist/imageview.js:19:16)
    at e (./dist/imageview.js:20:16)
    at f (./dist/imageview.js:21:16)
    at g (./dist/imageview.js:22:16)
    at h (./dist/imageview.js:23:16)
    at i (./dist/imageview.js:24:16)
    at j (./dist/imageview.js:25:16)
```

**Comment by tbuschto** [comment]
Related: https://stackoverflow.com/questions/7697038/more-than-10-lines-in-a-node-js-stack-error

**Comment by mpost** [comment]
The stack trace length has been increased to 256 by default. It can also be user controlled by setting: `Error.stackTraceLimit = <limit>` (also supports `Infinity`).
