### ISSUE TITLE
Serve Failure on MacOS

### ISSUE THREAD

**Issue by raphaelpreston** [eclipsesource/tabris-js#1803]
### Problem description
Unable to serve, fails on `TypeError: networkUtils.qualityFromDB is not a function`.

### Environment

- Tabris.js version: nightly (3.0.0-beta2-dev.20190228)
- OS: macOS Sierra 10.12.6

### Console Output

```
News-MacBook-Pro:Documents developer$ git clone https://github.com/raphaelpreston/TabrisExample.git
Cloning into 'TabrisExample'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (19/19), done.
remote: Total 23 (delta 5), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (23/23), done.
News-MacBook-Pro:Documents developer$ cd TabrisExample/
News-MacBook-Pro:TabrisExample developer$ ls
cordova		package.json	src
News-MacBook-Pro:TabrisExample developer$ npm install
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm notice created a lockfile as package-lock.json. You should commit this file.
added 131 packages from 139 contributors and audited 203 packages in 4.901s
found 0 vulnerabilities

News-MacBook-Pro:TabrisExample developer$ tabris --version
3.0.0-beta2-dev.20190227
News-MacBook-Pro:TabrisExample developer$ tabris serve
[/Users/developer/Documents/TabrisExample] npm run --if-present build
/usr/local/lib/node_modules/tabris-cli/node_modules/node-wifi/src/mac-current-connections.js:14
            connection.quality = networkUtils.qualityFromDB(parseInt(line.match(/[ ]*agrCtlRSSI: (.*)/)[1]));
                                              ^

TypeError: networkUtils.qualityFromDB is not a function
    at /usr/local/lib/node_modules/tabris-cli/node_modules/node-wifi/src/mac-current-connections.js:14:47
    at Array.forEach (<anonymous>)
    at parseAirport (/usr/local/lib/node_modules/tabris-cli/node_modules/node-wifi/src/mac-current-connections.js:11:11)
    at /usr/local/lib/node_modules/tabris-cli/node_modules/node-wifi/src/mac-current-connections.js:42:40
    at ChildProcess.exithandler (child_process.js:285:7)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)
```

**Comment by cookieguru** [comment]
This should be in https://github.com/eclipsesource/tabris-js-cli/

Looks like an issue with one of the [dependencies](https://github.com/eclipsesource/tabris-js-cli/blob/master/package.json#L15): https://github.com/friedrith/node-wifi/issues/57

As a workaround you can modify the [`selectAddressForQRCode()` function](https://github.com/eclipsesource/tabris-js-cli/blob/a87e7875f7a4495a5168320fb14ab97e205b8bce/src/services/ServerInfo.js#L33) in `
/usr/local/lib/node_modules/tabris-cli/src/services/ServerInfo.js` so that it is just one line:
```js
return Promise.resolve(this.externalAddresses[0]);
```
The QR code might not be pointing to the best address though.
