### ISSUE TITLE
Developer app crashes on iOS 13 beta 7

### ISSUE THREAD

**Issue by patrykmol** [eclipsesource/tabris-js#1926]
### Problem description

Tabris.js 3 is crashing on iOS 13 beta 7.

### Expected behavior

App should launch.

### Environment

- Tabris.js version: 3.x nightly
- Device: iPad Pro 1st gen
- OS: iOS 13 beta 7

### Code snippet

Just start developer app.
```
Could not load main module: TypeError: Proxy object's 'set' trap returned falsy value for property '_callbacks'
  at on (file:///var/containers/Bundle/Application/4731AE54-6332-47B5-BB88-F6A1CB677D24/Tabris.js.app/www/app/node_modules/tabris/tabris.js:1817:9)
  at addListener (file:///var/containers/Bundle/Application/4731AE54-6332-47B5-BB88-F6A1CB677D24/Tabris.js.app/www/app/node_modules/tabris/tabris.js:1993:20)
  at UrlView (file:///var/containers/Bundle/Application/4731AE54-6332-47B5-BB88-F6A1CB677D24/Tabris.js.app/www/app/dist/src/widget/UrlView.js:25:38)
  at createNativeObject (file:///var/containers/Bundle/Application/4731AE54-6332-47B5-BB88-F6A1CB677D24/Tabris.js.app/www/app/node_modules/tabris/tabris.js:2136:28)
  at value (file:///var/containers/Bundle/Application/4731AE54-6332-47B5-BB88-F6A1CB677D24/Tabris.js.app/www/app/node_modules/tabris/tabris.js:7526:128)
  at showApp (file:///var/containers/Bundle/Application/4731AE54-6332-47B5-BB88-F6A1CB677D24/Tabris.js.app/www/app/dist/src/app.js:46:26)
  at file:///var/containers/Bundle/Application/4731AE54-6332-47B5-BB88-F6A1CB677D24/Tabris.js.app/www/app/dist/src/app.js:19:12
  at get (file:///var/containers/Bundle/Application/4731AE54-6332-47B5-BB88-F6A1CB677D24/Tabris.js.app/www/app/node_modules/tabris/boot.min.js:1:780)
  at value (file:///var/containers/Bundle/Application/4731AE54-6332-47B5-BB88-F6A1CB677D24/Tabris.js.app/www/app/node_modules/tabris/boot.min.js:1:1365)
  at o (file:///var/containers/Bundle/Application/4731AE54-6332-47B5-BB88-F6A1CB677D24/Tabris.js.app/www/app/node_modules/tabris/boot.min.js:1:3467)
  at file:///var/containers/Bundle/Application/4731AE54-6332-47B5-BB88-F6A1CB677D24/Tabris.js.app/www/cordova.js:713:16
  at file:///var/containers/Bundle/Application/4731AE54-6332-47B5-BB88-F6A1CB677D24/Tabris.js.app/www/cordova.js:133:43
  at file:///var/containers/Bundle/Application/4731AE54-6332-47B5-BB88-F6A1CB677D24/Tabris.js.app/www/cordova.js:1428:34
  at file:///var/containers/Bundle/Application/4731AE54-6332-47B5-BB88-F6A1CB677D24/Tabris.js.app/www/app/node_modules/tabris/boot.min.js:1:3623
```

**Comment by tbuschto** [comment]
This looks like a bug in the JS Engine, specifically [Reflect.set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect/set), which either incorrectly returns true or incorrectly fails to set the _callbacks property.

This is the line in question: https://github.com/eclipsesource/tabris-js/blob/15e4ef402c89c06907a43a267dc23cbfbd8d7afe/src/tabris/util.js#L114

**Comment by DasHasan** [comment]
Any news on this?

**Comment by patrykmol** [comment]
This has been fixed by https://github.com/eclipsesource/tabris-js/commit/1685effbfc1e9adb78977fb9c1988bb37bf1f667 afaik. Closing.
