### ISSUE TITLE
Initialization failed

### ISSUE THREAD

**Issue by OverflowCat** [eclipsesource/tabris-js#1931]
### `tabris init` failed
```shell
async serve(appPath, main) {
   ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/tabris-cli/src/serve.js:4:16)
```
### Environment
CentOS 7, Virmach
NodeJS 6.17.1

The same problem arose when I tried to start an existing project on my VPS:
![D758743C-AC9B-4129-A979-F6C8B3DC7AC9](https://user-images.githubusercontent.com/20166026/63766265-651a1500-c8fd-11e9-8c53-bf77c3fe99a0.jpeg)

**Comment by mpost** [comment]
Since the proposed solution is correct, i'll close this issue for now. Please reopen if you find that this is a general problem on the tabris side.
