### ISSUE TITLE
Some Tabris.js 2.x app builds using webpack might fail

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#1997]
### Problem description

Builds using webpack and ts-loader >=5.4.5 are failing due to https://github.com/TypeStrong/ts-loader/issues/929:

```
Entrypoint main = index.js
[0] ./src/index.js 3.54 KiB {0} [not cacheable] [built] [failed] [1 error]
ERROR in ./src/index.js
Module build failed (from ./node_modules/ts-loader/index.js):
/home/travis/build/eclipsesource/tabris-js-build-template/build/node_modules/micromatch/index.js:44
    let isMatch = picomatch(String(patterns[i]), { ...options, onResult }, [secure]);
                                                   ^^^
SyntaxError: Unexpected token ...
    at NativeCompileCache._moduleCompile (/home/travis/build/eclipsesource/tabris-js-build-template/build/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/home/travis/build/eclipsesource/tabris-js-build-template/build/node_modules/webpack-cli/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
```

### Environment

- Tabris.js version: 2.9
- OS: Android

**Comment by cpetrov** [comment]
The Node.js version used in the Tabris.js 2.x Android build configuration was outdated. 

The Node.js version was updated to 12.x.x (current LTS) for all build configurations for apps built with Tabris.js 2 and 3.
