### ISSUE TITLE
Cannot append empty WidgetCollection nested inside <$/>

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#2032]
### Problem description

When appending `<$></$>` containing an empty `WidgetCollection`, an error is thrown.

### Environment

- Tabris.js version: 3.4.0

### Code snippet

```jsx
import {contentView, WidgetCollection} from 'tabris';

contentView.append(
  <$>
    <WidgetCollection />
  </$>
);
```

```log
>  Could not load main module: Error: Cannot append non-widget "" to ContentView[cid="$3"]
     at /home/cpetrov/git/tabris-js/snippets/dist/composite.js:4:22
     at subscribe (./cordova.js:758:11)
     at addEventListener (./cordova.js:133:34)
     at ./cordova.js:1560:18
```

**Comment by macelux** [comment]
i get the same eroor too
