### ISSUE TITLE
Online build fails

### ISSUE THREAD

**Issue by Joshua-Beatty** [eclipsesource/tabris-js#2033]
### Problem description

When using the online build system the build fails

### Expected behavior

I expected for the build to succeed

### Environment

- Tabris.js version: 3.4.1
- Device: N/A
- OS: Online Build system, building to Ios

### Build log
Here is what I believe is the relevant part of the build log. 
```
Signing Identity:     "Apple Distribution: Joshua Beatty (MA7295ZH6L)"
Provisioning Profile: "Circle Calc Profile"
                      (1668ee63-b924-4a43-ac44-f683b05e1108)
    /usr/bin/codesign --force --sign 735932F2D02635F953772F25535BD0E636629A20 --entitlements /Users/travis/Library/Developer/Xcode/DerivedData/Circle_Calc.-bhrivdxygllqokeikbuedtpuhxxr/Build/Intermediates.noindex/ArchiveIntermediates/Circle\ Calc./IntermediateBuildFilesPath/Circle\ Calc..build/Release-iphoneos/Circle\ Calc..build/Circle\ Calc..app.xcent /Users/travis/Library/Developer/Xcode/DerivedData/Circle_Calc.-bhrivdxygllqokeikbuedtpuhxxr/Build/Intermediates.noindex/ArchiveIntermediates/Circle\ Calc./InstallationBuildProductsLocation/Applications/Circle\ Calc..app
Validate /Users/travis/Library/Developer/Xcode/DerivedData/Circle_Calc.-bhrivdxygllqokeikbuedtpuhxxr/Build/Intermediates.noindex/ArchiveIntermediates/Circle\ Calc./InstallationBuildProductsLocation/Applications/Circle\ Calc..app (in target 'Circle Calc.' from project 'Circle Calc.')
    cd /Users/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/ios
    builtin-validationUtility /Users/travis/Library/Developer/Xcode/DerivedData/Circle_Calc.-bhrivdxygllqokeikbuedtpuhxxr/Build/Intermediates.noindex/ArchiveIntermediates/Circle\ Calc./InstallationBuildProductsLocation/Applications/Circle\ Calc..app
Touch /Users/travis/Library/Developer/Xcode/DerivedData/Circle_Calc.-bhrivdxygllqokeikbuedtpuhxxr/Build/Intermediates.noindex/ArchiveIntermediates/Circle\ Calc./InstallationBuildProductsLocation/Applications/Circle\ Calc..app (in target 'Circle Calc.' from project 'Circle Calc.')
    cd /Users/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/ios
    /usr/bin/touch -c /Users/travis/Library/Developer/Xcode/DerivedData/Circle_Calc.-bhrivdxygllqokeikbuedtpuhxxr/Build/Intermediates.noindex/ArchiveIntermediates/Circle\ Calc./InstallationBuildProductsLocation/Applications/Circle\ Calc..app
** ARCHIVE SUCCEEDED **
Command finished with error code 0: xcodebuild -workspace,Circle Calc..xcworkspace,-scheme,Circle Calc.,-configuration,Release,-destination,generic/platform=iOS,-archivePath,Circle Calc..xcarchive,archive,CONFIGURATION_BUILD_DIR=/Users/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/ios/build/device,SHARED_PRECOMPS_DIR=/Users/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/ios/build/sharedpch
Running command: xcodebuild -exportArchive -archivePath Circle Calc..xcarchive -exportOptionsPlist /Users/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/ios/exportOptions.plist -exportPath /Users/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/ios/build/device
2020-04-22 08:37:18.190 xcodebuild[3665:9255] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/Circle Calc._2020-04-22_08-37-18.189.xcdistributionlogs'.
error: exportArchive: Couldn't find platform family for "term-size".
Error Domain=DVTFoundationNSBundleAdditionsErrorDomain Code=1 "Couldn't find platform family for "term-size"." UserInfo={NSLocalizedDescription=Couldn't find platform family for "term-size"., NSLocalizedRecoverySuggestion=Coulnd't find CFBundleSupportedPlatforms in the Info.plist or LC_VERSION_MIN in the Mach-O for path "/Users/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/ios/Circle Calc..xcarchive/Products/Applications/Circle Calc..app/www/app/node_modules/term-size/vendor/macos/term-size".}
** EXPORT FAILED **
Command finished with error code 70: xcodebuild -exportArchive,-archivePath,Circle Calc..xcarchive,-exportOptionsPlist,/Users/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/ios/exportOptions.plist,-exportPath,/Users/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/ios/build/device
xcodebuild: Command failed with exit code 70
Error: xcodebuild: Command failed with exit code 70
    at ChildProcess.whenDone (/Users/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/ios/cordova/node_modules/cordova-common/src/superspawn.js:135:23)
    at ChildProcess.emit (events.js:310:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
The command /Users/travis/.tabris-cli/cordova/9.0.0/node_modules/.bin/cordova exited with 70
Warning: Command failed: tabris build ios  --release --device --verbose --cordova-build-config="../../../tabrisBuildConfig.json"
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN tabris-cli-cordova-9.0.0-cache@3.4.1 No description
npm WARN tabris-cli-cordova-9.0.0-cache@3.4.1 No repository field.
npm WARN tabris-cli-cordova-9.0.0-cache@3.4.1 No license field.
2020-04-22 08:37:18.190 xcodebuild[3665:9255] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/17/5mc7816d3mndxjqgplq6057w0000gn/T/Circle Calc._2020-04-22_08-37-18.189.xcdistributionlogs'.
error: exportArchive: Couldn't find platform family for "term-size".
Error Domain=DVTFoundationNSBundleAdditionsErrorDomain Code=1 "Couldn't find platform family for "term-size"." UserInfo={NSLocalizedDescription=Couldn't find platform family for "term-size"., NSLocalizedRecoverySuggestion=Coulnd't find CFBundleSupportedPlatforms in the Info.plist or LC_VERSION_MIN in the Mach-O for path "/Users/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/ios/Circle Calc..xcarchive/Products/Applications/Circle Calc..app/www/app/node_modules/term-size/vendor/macos/term-size".}
xcodebuild: Command failed with exit code 70
The command /Users/travis/.tabris-cli/cordova/9.0.0/node_modules/.bin/cordova exited with 70
 Use --force to continue.
Aborted due to warnings.
travis_time:end:299437a4:start=1587544441650655000,finish=1587544654188068000,duration=212537413000,event=script
The command "grunt build deploy" exited with 6.
travis_fold:start:after_failure
travis_time:start:02736c00
$ sleep 3
travis_time:end:02736c00:start=1587544654207120000,finish=1587544657250060000,duration=3042940000,event=after_failure
travis_fold:end:after_failure
travis_fold:start:after_script.1
travis_time:start:04e40776
$ security delete-keychain ios-build.keychain
travis_time:end:04e40776:start=1587544657264327000,finish=1587544657425784000,duration=161457000,event=after_script
travis_fold:end:after_script.1
travis_fold:start:after_script.2
travis_time:start:0ad5f411
$ rm -f ~/Library/MobileDevice/Provisioning\ Profiles/*
travis_time:end:0ad5f411:start=1587544657440168000,finish=1587544657452051000,duration=11883000,event=after_script
travis_fold:end:after_script.2

Done. Your build exited with 1.
```

**Comment by karolszafranski** [comment]
It looks like there is a binary called `term-size` in one of the node modules included in your app. From what I see in the module description it doesn't look useful for Tabris.js application. Can you remove it from your app dependencies in package.json? This should fix the build.

https://www.npmjs.com/package/term-size

**Comment by Joshua-Beatty** [comment]
Thank you!
I am new to Node js so i made this mistake in my package.lock file:
<pre><code>
"dependencies": {
    "big.js": "^5.2.2",
    "tabris": "^3.4.0",
    <b>"tabris-cli": "^3.4.1"</b>
  },
</code></pre>
After removing tabris-cli the build passed
