### ISSUE TITLE
Cordova ContentProvider plugins makes tabris app crash

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/tabris-js#2045]
It can be my mistake  but all the cordova plugins I installed that use the contentProvider or media provider feature make a Tabris application crash.
https://github.com/r-cohen/cordova-ContentProviderPlugin
https://github.com/jtsamper/cordova-plugin-document-contract

**Comment by mpost** [comment]
Could you provide a stacktrace of the crash?

**Comment by ishigo1987** [comment]
The problem is that adb logcat doesn't return anything meaningful if you can please take some time to try these plugins. 
Thank you

**Comment by mpost** [comment]
At what point does it crash? During build, app startup or usage of the APIs?

**Comment by ishigo1987** [comment]
Usage of the api

**Comment by cookieguru** [comment]
@ishigo1987 do you have a code snippet that can reproduce the crash?

**Comment by ishigo1987** [comment]
```JAVASCRIPT
window.plugins.contentproviderplugin.query({
		contentUri: "content://sms/inbox",
		projection: ["address", "date", "body"],
		selection: null,
		selectionArgs: null,
		sortOrder: "date DESC"
	}, function (data) {
		console.log(JSON.stringify(data));
	}, function (err) {
		console.log("error query");
	});
```
use case of this plugin https://github.com/r-cohen/cordova-ContentProviderPlugin
with the sms permission added

**Comment by mpost** [comment]
I have tested the plugin and found it to work as expected. You have to make sure to give the SMS permission and grant it. Otherwise the plugin crashes with

```error 
java.lang.SecurityException: Permission Denial: reading com.android.providers.telephony.SmsProvider uri content://sms/inbox from pid=16722, uid=10307 requires android.permission.READ_SMS, or grantUriPermission()
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at android.content.ContentResolver.query(ContentResolver.java:836)
        at com.phearme.cordovaplugin.ContentProviderPlugin.runQuery(ContentProviderPlugin.java:101)
        at com.phearme.cordovaplugin.ContentProviderPlugin.access$000(ContentProviderPlugin.java:12)
        at com.phearme.cordovaplugin.ContentProviderPlugin$1.run(ContentProviderPlugin.java:28)
```

Make sure to include the SMS_READ permission in your config.xml.

```xml
<platform name="android">
    <edit-config file="app/src/main/AndroidManifest.xml" target="/manifest/application" mode="merge">
      <application android:usesCleartextTraffic="true"/>
    </edit-config>
    <config-file target="app/src/main/AndroidManifest.xml" parent="/manifest">
      <uses-permission android:name="android.permission.READ_SMS"/>
    </config-file>
  </platform>
```

And [request the permission during runtime](https://docs.tabris.com/latest/permissions.html#requesting-permissions).

```js
await permission.requestAuthorization('android.permission.READ_SMS');
```

**Comment by ishigo1987** [comment]
Thank you
