### ISSUE TITLE
Access to fs.readFile throws exception in worker

### ISSUE THREAD

**Issue by tbuschto** [eclipsesource/tabris-js#2162]
### Environment

- Tabris.js version: 3.7
- Device: OnePlus 7 Pro
- OS: Android 10

### Code snippet

```js
// eslint-disable-next-line no-undef
const {Button, TextInput, TextView, contentView, fs} = require('tabris');

// Create a worker that receives two numbers, adds them and sends the result back to the main script

console.log('hello worker');
const number1 = new TextInput({centerX: -65, top: 24, width: 32, alignment: 'centerX', text: '2'})
  .appendTo(contentView);
new TextView({left: 'prev() 16', baseline: 'prev()', text: '+'})
  .appendTo(contentView);
const number2 = new TextInput({left: 'prev() 16', baseline: 'prev()', width: 32, alignment: 'centerX', text: '3'})
  .appendTo(contentView);
new TextView({left: 'prev() 16', baseline: 'prev()', text: '='})
  .appendTo(contentView);
const result = new TextView({left: 'prev() 24', baseline: 'prev()', text: '?'})
  .appendTo(contentView);

new Button({
  left: 16, right: 16, top: [number1, 16],
  text: 'Add numbers in Worker'
}).onSelect(() => {
  const worker = new Worker('resources/worker-script.js');
  worker.onmessage = (event) => {
    result.text = event.data;
    worker.terminate();
  };
  worker.onerror = (error) => {
    console.log(`onerror: ${JSON.stringify(error)}`);
    worker.terminate();
  };
  const data = new Uint8ClampedArray([parseInt(number1.text, 10), parseInt(number2.text, 10)]);
  const path = fs.cacheDir + '/' + Date.now();
  fs.writeFile(path, data).then(() => {
    worker.postMessage(path);
  });
}).appendTo(contentView);
```
And the `worker-script.js`:

```js
const {fs} = require('tabris');

console.log('Worker running...');

onmessage = e => {
  console.log('Message received from main script. ' + JSON.stringify(e));
  fs.readFile(e.data).then(buffer => {
    const data = new Uint8ClampedArray(buffer);
    const number1 = data[0];
    const number2 = data[1];
    console.log(`Adding numbers ${number1} and ${number2}`);
    const result = number1 + number2;
    console.log('Posting result of ' + result + ' to main script');
    postMessage(result);
  });
};
```

This works fine in iOS, but on Android the following error is logged:

```
Uncaught promise rejection (id: 0) Error: Invalid V8 thread access: current thread is Thread[main,5,main] while the locker has thread Thread[Thread-18,5,main]: /data/user/0/com.eclipsesource.tabris.js/cache/1617739301485
Error: Invalid V8 thread access: current thread is Thread[main,5,main] while the locker has thread Thread[Thread-18,5,main]: /data/user/0/com.eclipsesource.tabris.js/cache/1617739301485
    at createError (./node_modules/tabris/tabris.min.js:1:136038)
    at onError (./node_modules/tabris/tabris.min.js:1:132916)
```

File system access is supported according to https://docs.tabris.com/3.7/w3c-api.html#worker

**Comment by mpost** [comment]
Fixed in nightly.
