### ISSUE TITLE
apk builds on cloud for android fails

### ISSUE THREAD

**Issue by bezkel** [eclipsesource/tabris-js#2207]
### Problem description

My builds for android in cloudservice doesnt work. The last one three days ago was working. I tried it also with another version that was definitly working. 
ios, by the way, is working.

I tried it with two different apps. Both went into the same error.
It seems like something went wrong with gradle.

### Expected behavior

Build the apk ;)

### Environment

- Tabris.js version: 3.8.0

### Snippet from detail log where it fails

```
Welcome to Gradle 6.5!
Here are the highlights of this release:
 - Experimental file-system watching
 - Improved version ordering
 - New samples
For more details see https://docs.gradle.org/6.5/release-notes.html
To honour the JVM settings for this build a new JVM will be forked. Please consider using the daemon: https://docs.gradle.org/6.5/userguide/gradle_daemon.html.
Daemon will be stopped at the end of the build stopping after processing
> Configure project :app
Warning: The 'kotlin-android-extensions' Gradle plugin is deprecated. Please use this migration guide (https://goo.gle/kotlin-android-extensions-deprecation) to start working with View Binding (https://developer.android.com/topic/libraries/view-binding) and the 'kotlin-parcelize' plugin.
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':CordovaLib:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':CordovaLib:debugCompileClasspath'.
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.4.32.
     Required by:
         project :CordovaLib
      > Skipped due to earlier error
      > Skipped due to earlier error
   > Could not resolve com.eclipsesource.j2v8:j2v8:6.2.1.
     Required by:
         project :CordovaLib > com.eclipsesource.tabris.android:tabris:3.8.0
      > Skipped due to earlier error
      > Skipped due to earlier error
   > Could not resolve org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.21.
     Required by:
         project :CordovaLib > com.eclipsesource.tabris.android:tabris:3.8.0
      > Skipped due to earlier error
      > Skipped due to earlier error
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
BUILD FAILED in 3m 43s
Command failed with exit code 1: /home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/android/gradlew cdvBuildDebug -b /home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/android/build.gradle
Error: Command failed with exit code 1: /home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/android/gradlew cdvBuildDebug -b /home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/android/build.gradle
    at makeError (/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/android/cordova/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/travis/build/eclipsesource/tabris-js-build-template/build/build/cordova/platforms/android/cordova/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
The command /home/travis/.tabris-cli/cordova/9.0.0/node_modules/.bin/cordova exited with 1
```

**Comment by mpost** [comment]
This looks like it could be related to a maven central outage. Could you try again?

**Comment by bezkel** [comment]
Works now, thank you 👍
