### ISSUE TITLE
Android remote debugger is not working

### ISSUE THREAD

**Issue by Barif1979** [eclipsesource/tabris-js#2253]
### Problem description

With tabris 3.9 debugging on Android doesn't work with local builds or with cloud builds.

### Expected behavior

the behavior I expect is to have the debug bar with the "wait for debugger" option and be able to connect from VSCODE or Chrome Inspector.
What I get is an app that has the debug bar and the right menu but not the "wait for debugger" option, moreover both chrome and vscode do not connect either by entering the ip or by forwarding the ports and connecting to the localhost , they just don't connect.
Even forcing chrome like this:

`adb forward tcp:9090 tcp:9090`

and visiting the url:

`devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=localhost:9090`

i get nothing. it should be noted that the debugger options are enabled and other cordova applications I can debug them without problems.

### Environment

- Tabris.js version: 3.9
- Device: many: Galaxy A8, Vodafone V8, Redmi GO. (Android11, Android10, Android 8.1 go)
- OS: Android from 8.1 to 11 on test phones, Ubuntu 22.04.1 LTS as dev machine.
- Build: local, ubuntu jsk11, cloud, your service.

**Comment by Barif1979** [comment]
I add more details: after forwarding the ports via ADB:
`adb forward tcp:9090 tcp:9090`
(obviously the device is plugged in and adb devices reports it correctly)
`List of devices attached
c863d0da7cf6    device
`
this is the visualstudio code log when i try to hook debug:
`[
  {
    "tag": "runtime.launch",
    "timestamp": 1674491203826,
    "message": "Launch returned error",
    "metadata": {
      "error": {
        "message": "Could not connect to debug target at http://localhost:9090: Could not find any debuggable target",
        "stack": "Error: Could not connect to debug target at http://localhost:9090: Could not find any debuggable target\n\tat /usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1161605\n\tat process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n\tat async t (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1187125)\n\tat async C.launch (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1204540)\n\tat async t.Binder.captureLaunch (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:985758)\n\tat async t.Binder._launch (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:985303)\n\tat async Promise.all (index 5)\n\tat async t.Binder._boot (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:984403)\n\tat async t.default._onMessage (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1082470)"
      },
      "wasCancelled": true,
      "name": "C"
    },
    "level": 2
  },
  {
    "tag": "dap.send",
    "timestamp": 1674491203826,
    "metadata": {
      "connectionId": 3,
      "message": {
        "seq": 9,
        "type": "response",
        "request_seq": 2,
        "command": "attach",
        "success": false,
        "body": {
          "error": {
            "id": 9221,
            "format": "Error processing attach: Error: Could not connect to debug target at http://localhost:9090: Could not find any debuggable target\n\tat /usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1161605\n\tat process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n\tat async t (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1187125)\n\tat async C.launch (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1204540)\n\tat async t.Binder.captureLaunch (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:985758)\n\tat async t.Binder._launch (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:985303)\n\tat async Promise.all (index 5)\n\tat async t.Binder._boot (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:984403)\n\tat async t.default._onMessage (/usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js:2:1082470)",
            "showUser": false,
            "sendTelemetry": false
          }
        }
      }
    },
    "level": 0
  }
]`
