### ISSUE TITLE
Build error: MainActivity.java:20: error: <identifier> expected package game.for.lina;

### ISSUE THREAD

**Issue by andreasmihm** [eclipsesource/tabris-js#453]
I created a new tabrisjs project and got it validated on tabrisjs.com, but when I try to build it, I get the following error. Why do I get the error during build?

I paste the config.xml, package,json and the build log file  below

############ config.xml
```
<?xml version='1.0' encoding='utf-8'?>
<widget
    id="game.for.lina"
    version="1.0.0"
    xmlns:gap="http://phonegap.com/ns/1.0"
    xmlns="http://www.w3.org/ns/widgets"
    xmlns:cdv="http://cordova.apache.org/ns/1.0">
 
    <name>Spiel Für Lina</name>
    <description>
        Spiel für Lina
    </description>
    <author email="me@me.com" href="http://www.me.me">
        Me
    </author>
 
    <access origin="*" />
 
    <preference name="EnableDeveloperConsole" value="false"/>
</widget>
```

###########package.json
```js
{
  "name": "game-for-lina",
  "description": "Spiel für Lina",
  "main": "app.js",
  "dependencies": {
    "tabris": "1.0.0"
  }
}
```

############build error from log file
```
AAPT warning(Job{title=Cruncher btn_check_label_background.9.png, latch=BooleanLatch{signaled=false}, result=false}): /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/intermediates/exploded-aar/com.eclipsesource.tabris/tabris-android/2.0.0/res/drawable-mdpi-v17/btn_check_label_background.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT warning(Job{title=Cruncher ic_drawer.png, latch=BooleanLatch{signaled=false}, result=false}): /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/intermediates/exploded-aar/com.eclipsesource.tabris/tabris-android/2.0.0/res/drawable-mdpi-v4/ic_drawer.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
:processDebugManifest
:processDebugResources
:generateDebugSources
:compileDebugJava/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/src/game/for/lina/MainActivity.java:20: error: <identifier> expected
package game.for.lina;
             ^
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/src/game/for/lina/MainActivity.java:20: error: class, interface, or enum expected
package game.for.lina;
                ^
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/src/game/for/lina/MainActivity.java:20: error: class, interface, or enum expected
package game.for.lina;
                 ^
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/generated/source/r/debug/game/for/lina/R.java:8: error: <identifier> expected
package game.for.lina;
             ^
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/generated/source/r/debug/game/for/lina/R.java:8: error: class, interface, or enum expected
package game.for.lina;
                ^
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/generated/source/r/debug/game/for/lina/R.java:8: error: class, interface, or enum expected
package game.for.lina;
                 ^
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/generated/source/buildConfig/debug/game/for/lina/BuildConfig.java:4: error: <identifier> expected
package game.for.lina;
             ^
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/generated/source/buildConfig/debug/game/for/lina/BuildConfig.java:4: error: class, interface, or enum expected
package game.for.lina;
                ^
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/generated/source/buildConfig/debug/game/for/lina/BuildConfig.java:4: error: class, interface, or enum expected
package game.for.lina;
                 ^
9 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
 FAILED

BUILD FAILED

Total time: 51.823 secs

/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/cordova/build: Command failed with exit code 8
You may not have the required environment or OS to build this project
Error: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/cordova/build: Command failed with exit code 8
    at ChildProcess.whenDone (/home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
[33mWarning: Command failed: Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/CordovaLib/src/com/eclipsesource/tabris/android/cordova/CordovaPluginOperator.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/CordovaLib/src/com/eclipsesource/tabris/android/cordova/CordovaPluginOperator.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/src/game/for/lina/MainActivity.java:20: error: <identifier> expected
package game.for.lina;
             ^
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/src/game/for/lina/MainActivity.java:20: error: class, interface, or enum expected
package game.for.lina;
                ^
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/src/game/for/lina/MainActivity.java:20: error: class, interface, or enum expected
package game.for.lina;
                 ^
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/generated/source/r/debug/game/for/lina/R.java:8: error: <identifier> expected
package game.for.lina;
             ^
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/generated/source/r/debug/game/for/lina/R.java:8: error: class, interface, or enum expected
package game.for.lina;
                ^
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/generated/source/r/debug/game/for/lina/R.java:8: error: class, interface, or enum expected
package game.for.lina;
                 ^
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/generated/source/buildConfig/debug/game/for/lina/BuildConfig.java:4: error: <identifier> expected
package game.for.lina;
             ^
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/generated/source/buildConfig/debug/game/for/lina/BuildConfig.java:4: error: class, interface, or enum expected
package game.for.lina;
                ^
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build/generated/source/buildConfig/debug/game/for/lina/BuildConfig.java:4: error: class, interface, or enum expected
package game.for.lina;
                 ^
9 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build.gradle,-Dorg.gradle.daemon=true
Error: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/cordova/build: Command failed with exit code 8
    at ChildProcess.whenDone (/home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
 Use --force to continue.[39m

[31mAborted due to warnings.[39m
travis_time:end:0235232e:start=1432129412829661996,finish=1432129471371683961,duration=58542021965
[0K
[31;1mThe command "grunt build deploy" exited with 6.[0m

Done. Your build exited with 1.
```

**Comment by hstaudacher** [comment]
Hmm, just tried one of our apps to build with android, it works. So, it's not an infrastructure problem. Can you provide the source of the project to me? If you don't want to publish it just send it via mail to hstaudacher@eclipsesource.com

**Comment by andreasmihm** [comment]
Hi Holger,
the source is very simple, you find it at
https://github.com/andreasmihm/game.for.lina
~Andreas

**Comment by hstaudacher** [comment]
Working on it

**Comment by andreasmihm** [comment]
thx

**Comment by hstaudacher** [comment]
First impression, build works for iOS. It's an android problem. Investigating...

**Comment by hstaudacher** [comment]
Ok, found it. It seems that `id="game.for.lina"` will be used to generate some Java classes. The `for` keyword is not allowed in package names in Java. So, just change your id and remove `for` and everything is working. Will close this issue.
