### ISSUE TITLE
Support npm module "promise" version 7.0.3

### ISSUE THREAD

**Issue by cpetrov** [eclipsesource/tabris-js#540]
A ReferenceError is thrown from the "asap" module dependency: 

```javascript
ReferenceError: process is not defined
ReferenceError: process is not defined
    at requestFlush (./node_modules/promise/node_modules/asap/raw.js:76:24)
    at rawAsap (./node_modules/promise/node_modules/asap/raw.js:18:9)
    at handle (./node_modules/promise/lib/core.js:93:3)
    at finale (./node_modules/promise/lib/core.js:152:5)
    at resolve (./node_modules/promise/lib/core.js:142:3)
    at done (./node_modules/promise/lib/core.js:174:5)
    at Object.xhr.onload (./node_modules/whatwg-fetch/fetch.js:276:9)
    at Object.a.dispatchEvent (./node_modules/tabris/tabris.min.js:33:787)
    at F (./node_modules/tabris/tabris.min.js:34:5417)
    at I (./node_modules/tabris/tabris.min.js:34:5574)
```

To reproduce, start the fetch example with "promise" module version 7.0.3. Version 6.1.0 [works as expected](https://github.com/eclipsesource/tabris-js/issues/362).

**Comment by jkrause** [comment]
Version 7.x of npm module "promise" relies on the node core module ```process```. The tabris-js-node  module provides an implementation of several core node modules, also for process.

To enable npm module promise add the following line to the dependencies of you package.json:
```
    "tabris-js-node": "^0.1.0"
```
You also have to require this module in your code before requiring the promise module. See https://github.com/eclipsesource/tabris-js-node/blob/master/README.md

**Comment by ralfstx** [comment]
As of Tabris.js 1.6, Promise is included on all platforms.
