### ISSUE TITLE
Theme not working

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#565]
![2015-08-01-22-15-03](https://cloud.githubusercontent.com/assets/13051277/9023795/1b5e20ce-389b-11e5-8e83-f8fb01886053.png)

this is my repo. https://github.com/iteearmah/churchapp

**Comment by mpost** [comment]
@iteearmah The build hook script that your are referencing in the <code>config.xml</code> is in the wrong location. Instead of placing the scripts folder in the www folder (which would effectively ship the script with you app) you place the scripts folder directly in the root of the project (next to the www folder).

**Comment by gosia-eclipsesource** [comment]
@iteearmah Also the value of the Theme preference in <code>config.xml</code> should start with the app ID as given in the widget tag - in the case of your app "com.churchapp" instead of "com.eclipsesource.sandbox.theme".

**Comment by mpost** [comment]
@gosia-eclipsesource Good catch. That is correct. :)

**Comment by iteearmah** [comment]
Creating Cordova project for the Android platform:
	Path: platforms/android
	Package: com.churchapp
	Name: ChurchApp
	Activity: MainActivity
	Android target: android-22
Copying template files...
Android project created with cordova-android@4.0.2
Error: ENOENT, no such file or directory '/home/travis/build/eclipsesource/tabris-js-build-template/build/resources/android/res'
    at Object.fs.linkSync (fs.js:760:18)
    at copyRecursiveSync (/home/travis/build/eclipsesource/tabris-js-build-template/build/scripts/android/afterPlatformAdd.js:27:8)
    at module.exports (/home/travis/build/eclipsesource/tabris-js-build-template/build/scripts/android/afterPlatformAdd.js:11:5)
    at runScriptViaModuleLoader (/home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:152:18)
    at runScript (/home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:130:16)
    at /home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:115:20
    at _fulfilled (/home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/q/q.js:810:14
Warning: Command failed: Error: ENOENT, no such file or directory '/home/travis/build/eclipsesource/tabris-js-build-template/build/resources/android/res'
    at Object.fs.linkSync (fs.js:760:18)
    at copyRecursiveSync (/home/travis/build/eclipsesource/tabris-js-build-template/build/scripts/android/afterPlatformAdd.js:27:8)
    at module.exports (/home/travis/build/eclipsesource/tabris-js-build-template/build/scripts/android/afterPlatformAdd.js:11:5)
    at runScriptViaModuleLoader (/home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:152:18)
    at runScript (/home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:130:16)
    at /home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:115:20
    at _fulfilled (/home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/q/q.js:749:13)
    at /home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/q/q.js:810:14
 Use --force to continue.
Aborted due to warnings.
travis_time:end:19bdbbc8:start=1438639945929551411,finish=1438639948708409244,duration=2778857833

The command "grunt build deploy" exited with 6.
Done. Your build exited with 1.

**Comment by iteearmah** [comment]
Manage to create the resources/android/res/... the build worked

**Comment by iteearmah** [comment]
Theme still not applying...

**Comment by iteearmah** [comment]
changed <preference name="Theme" value="com.churchapp" /> to <preference name="Theme" value="com.churchapp.R.style.Theme" />
Now working.

**Comment by gosia-eclipsesource** [comment]
Good to hear that :) Could you let us know what you changed?

**Comment by mpost** [comment]
@iteearmah Would be interesting to hear what you have changed.
