### ISSUE TITLE
EMap plugin - Android fatal crash in release build

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#641]
The EMap plugin works great from debug build but always fails in release build

```java
10-05 08:53:52.649: E/AndroidRuntime(25597): FATAL EXCEPTION: main
10-05 08:53:52.649: E/AndroidRuntime(25597): Process: com.sdlportal.sdlmobile3, PID: 25597
10-05 08:53:52.649: E/AndroidRuntime(25597): java.lang.NoSuchMethodError: No static method zzch(Ljava/lang/String;)V in class Lcom/google/android/gms/common/internal/zzx; or its super classes (declaration of 'com.google.android.gms.common.internal.zzx' appears in /data/app/com.sdlportal.sdlmobile3-1/base.apk)
10-05 08:53:52.649: E/AndroidRuntime(25597): 	at com.google.android.gms.maps.MapFragment.getMapAsync(Unknown Source)
10-05 08:53:52.649: E/AndroidRuntime(25597): 	at com.eclipsesource.tabris.maps.MapHolderView.setOnMapReadyListener(MapHolderView.java:61)
10-05 08:53:52.649: E/AndroidRuntime(25597): 	at com.eclipsesource.tabris.maps.MapOperator$2.run(MapOperator.java:72)
10-05 08:53:52.649: E/AndroidRuntime(25597): 	at android.os.Handler.handleCallback(Handler.java:739)
10-05 08:53:52.649: E/AndroidRuntime(25597): 	at android.os.Handler.dispatchMessage(Handler.java:95)
10-05 08:53:52.649: E/AndroidRuntime(25597): 	at android.os.Looper.loop(Looper.java:145)
10-05 08:53:52.649: E/AndroidRuntime(25597): 	at android.app.ActivityThread.main(ActivityThread.java:5974)
10-05 08:53:52.649: E/AndroidRuntime(25597): 	at java.lang.reflect.Method.invoke(Native Method)
10-05 08:53:52.649: E/AndroidRuntime(25597): 	at java.lang.reflect.Method.invoke(Method.java:372)
10-05 08:53:52.649: E/AndroidRuntime(25597): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
```

**Comment by jonek** [comment]
Hi Brian,
have you tried to fork and build our tabris-maps-example project?

We currently have a working build (with non-debug key) of the example project https://github.com/eclipsesource/tabris-maps-example and it is working fine.
I sent you the apk via email.

Please reopen this issue at the https://github.com/eclipsesource/tabris-maps repo and let's continue over there. Thanks!

**Comment by bFlood** [comment]
I think I messed up the map key again, *sigh*. I'll report back in the other repo if I can't get it working, thanks for the reminder

your apk worked as expected on all android devices
