### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#681]
fyi - saw this come through in Play Store crash logs

```log
java.lang.NullPointerException
	at com.eclipsesource.tabris.android.internal.javascript.V8JavaScriptBridge.notifyEvent(V8JavaScriptBridge.java:232)
	at com.eclipsesource.tabris.android.internal.javascript.JavaScriptMessageSender.send(JavaScriptMessageSender.java:28)
	at com.eclipsesource.tabris.client.core.RemoteObject.notify(RemoteObject.java:102)
	at com.eclipsesource.tabris.client.core.RemoteObject.notify(RemoteObject.java:84)
	at com.eclipsesource.tabris.client.core.RemoteObject.notify(RemoteObject.java:79)
	at com.eclipsesource.tabris.android.internal.toolkit.Animation$AnimationStateListener.onAnimationEnd(Animation.java:148)
	at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1056)
	at android.animation.ValueAnimator.access$400(ValueAnimator.java:50)
	at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:644)
	at android.animation.ValueAnimator$AnimationHandler.run(ValueAnimator.java:660)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
	at android.view.Choreographer.doCallbacks(Choreographer.java:574)
	at android.view.Choreographer.doFrame(Choreographer.java:543)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5097)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
	at dalvik.system.NativeStart.main(Native Method)
```

Android version: Android 4.4
Device: Droid MAXX (obake-maxx)

**Comment by mpost** [comment]
Thanks for the heads up. This issue has been fixed in the current 1.4 update.
