### ISSUE TITLE
Samsung Galaxy S6 issue

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#686]
a user reported this issue when running on a Samsung Galaxy S6, unfortunately, I do not have any other info:

![image](https://cloud.githubusercontent.com/assets/404991/11343081/6f4c09b2-91d8-11e5-8165-b28c0f62990f.png)

**Comment by irbull** [comment]
For the upcoming TabrisJS release (December 2015) we have changed the way we package our JavaScript runtime. We found that many devices require a 'fallback' mode for V8 and this should be fixed now.

**Comment by bFlood** [comment]
thanks @irbull

**Comment by bFlood** [comment]
can yo u confirm this will work on Galaxy6 and Galaxy Notes? we just got another report that brand new Galaxy Notes have the same error

**Comment by bFlood** [comment]
fwiw, this looks like an Android 5.1-5.1.1 issue (but that is what is getting installed on a lot of new devices so its pretty important)

**Comment by irbull** [comment]
I can't confirm this as I don't have this device. @mpost Do we have one of these in the KA office?

**Comment by mpost** [comment]
The Samsung Galaxy S6 uses a [64bit CPU](http://www.gsmarena.com/samsung_galaxy_s6-6849.php) so i would expect that the user was running on an older version of Tabris.js. Starting from Tabris.js 1.4 he should be fine. With the latest version Tabris.js 1.5 we migrated to j2v8 3.1.1 which should remedy his problem.

**Comment by bFlood** [comment]
thanks @mpost , I will try that today. the user was running an app with tabris.js 1.4

**Comment by mpost** [comment]
@bFlood Great. Let us know if it works out.

**Comment by bFlood** [comment]
this still does not work, tested on Samsung S6 with Android 5.1.1

this is a critical issue for us

```
12-17 15:11:10.311: D/ActivityThread(30811): Added TimaKeyStore provider
12-17 15:11:10.341: I/InjectionManager(30811): Inside getClassLibPath + mLibMap{0=, 1=}
12-17 15:11:10.341: I/InjectionManager(30811): Inside getClassLibPath caller 
12-17 15:11:10.351: I/MultiDex(30811): VM with version 2.1.0 has multidex support
12-17 15:11:10.351: I/MultiDex(30811): install
12-17 15:11:10.351: I/MultiDex(30811): VM has multidex support, MultiDex support library is disabled.
12-17 15:11:10.361: W/System.err(30811): remove failed: ENOENT (No such file or directory) : /data/data/com.sdlportal.sdlmobile3/cache/.tabris/tabris-js-launcher-http-request-cache/journal.tmp
12-17 15:11:10.361: D/InjectionManager(30811): InjectionManager
12-17 15:11:10.361: D/InjectionManager(30811): fillFeatureStoreMap com.sdlportal.sdlmobile3
12-17 15:11:10.361: I/InjectionManager(30811): Constructor com.sdlportal.sdlmobile3, Feature store :{}
12-17 15:11:10.361: I/InjectionManager(30811): featureStore :{}
12-17 15:11:10.381: D/SecWifiDisplayUtil(30811): Metadata value : SecSettings2
12-17 15:11:10.401: I/Timeline(30811): Timeline: Activity_launch_request id:com.sdlportal.sdlmobile3 time:253307662
12-17 15:11:10.401: D/Activity(30811): performCreate Call Injection manager
12-17 15:11:10.401: I/InjectionManager(30811): dispatchOnViewCreated > Target : com.sdlportal.sdlmobile3.MainActivity isFragment :false
12-17 15:11:10.431: D/PhoneWindow(30811): *FMB* installDecor mIsFloating : false
12-17 15:11:10.431: D/PhoneWindow(30811): *FMB* installDecor flags : -2139029248
12-17 15:11:10.471: D/Activity(30811): performCreate Call Injection manager
12-17 15:11:10.471: I/InjectionManager(30811): dispatchOnViewCreated > Target : com.eclipsesource.tabris.android.TabrisActivity isFragment :false
12-17 15:11:10.481: D/SecWifiDisplayUtil(30811): Metadata value : SecSettings2
12-17 15:11:10.481: D/OpenGLRenderer(30811): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
12-17 15:11:10.481: D/PhoneWindow(30811): *FMB* isFloatingMenuEnabled mFloatingMenuBtn : null
12-17 15:11:10.481: D/PhoneWindow(30811): *FMB* isFloatingMenuEnabled return false
12-17 15:11:10.501: D/SRIB_DCS(30811): log_dcs ThreadedRenderer::initialize entered! 
12-17 15:11:10.511: D/libEGL(30811): loaded /vendor/lib64/egl/libGLES_mali.so
12-17 15:11:10.531: I/OpenGLRenderer(30811): Initialized EGL, version 1.4
12-17 15:11:10.531: I/OpenGLRenderer(30811): HWUI protection enabled for context ,  &this =0x7fa86f58e0 ,&mEglDisplay = 1 , &mEglConfig = -1819577680 
12-17 15:11:10.531: D/OpenGLRenderer(30811): Get maximum texture size. GL_MAX_TEXTURE_SIZE is 8192
12-17 15:11:10.531: D/OpenGLRenderer(30811): Enabling debug mode 0
12-17 15:11:10.531: D/mali_winsys(30811): new_window_surface returns 0x3000,  [1440x2560]-format:1
12-17 15:11:10.551: W/Settings(30811): Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
12-17 15:11:10.591: I/WebViewFactory(30811): Loading com.google.android.webview version 46.0.2490.76 (code 249007650)
12-17 15:11:10.591: I/InjectionManager(30811): Inside getClassLibPath caller 
12-17 15:11:10.591: I/cr.library_loader(30811): Time to load native libraries: 1 ms (timestamps 7856-7857)
12-17 15:11:10.591: I/cr.library_loader(30811): Expected native library version number "46.0.2490.76", actual native library version number "46.0.2490.76"
12-17 15:11:10.601: V/WebViewChromiumFactoryProvider(30811): Binding Chromium to main looper Looper (main, tid 1) {3f491c5}
12-17 15:11:10.601: I/cr.library_loader(30811): Expected native library version number "46.0.2490.76", actual native library version number "46.0.2490.76"
12-17 15:11:10.601: I/chromium(30811): [INFO:library_loader_hooks.cc(118)] Chromium logging enabled: level = 0, default verbosity = 0
12-17 15:11:10.601: I/cr.BrowserStartup(30811): Initializing chromium process, singleProcess=true
12-17 15:11:10.601: E/SysUtils(30811): ApplicationContext is null in ApplicationStatus
12-17 15:11:10.621: E/chromium(30811): [ERROR:browser_gpu_channel_host_factory.cc(258)] Failed to init browser shader disk cache.
12-17 15:11:10.631: W/cr.media(30811): Requires BLUETOOTH permission
12-17 15:11:10.631: E/libEGL(30811): validate_display:255 error 3008 (EGL_BAD_DISPLAY)
12-17 15:11:10.641: I/art(30811): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>
12-17 15:11:10.641: I/art(30811): Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>
12-17 15:11:10.651: I/art(30811): Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingWebActionModeCallback>
12-17 15:11:10.651: I/art(30811): Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingWebActionModeCallback>
12-17 15:11:10.661: W/art(30811): Attempt to remove local handle scope entry from IRT, ignoring
12-17 15:11:10.671: W/AwContents(30811): onDetachedFromWindow called when already detached. Ignoring
12-17 15:11:10.671: D/JsMessageQueue(30811): Set native->JS mode to NoOpBridgeMode
12-17 15:11:10.671: D/SystemWebViewEngine(30811): CordovaWebView is running on device made by: samsung
12-17 15:11:10.681: W/art(30811): Attempt to remove local handle scope entry from IRT, ignoring
12-17 15:11:10.681: W/art(30811): Attempt to remove local handle scope entry from IRT, ignoring
12-17 15:11:10.681: D/SecWifiDisplayUtil(30811): Metadata value : SecSettings2
12-17 15:11:10.701: E/Tabris(30811): Could not execute JavaScript
12-17 15:11:10.701: E/Tabris(30811): java.lang.IllegalStateException: J2V8 native library not loaded.
12-17 15:11:10.701: E/Tabris(30811): 	at com.eclipsesource.v8.V8.checkNativeLibraryLoaded(V8.java:149)
12-17 15:11:10.701: E/Tabris(30811): 	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:135)
12-17 15:11:10.701: E/Tabris(30811): 	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:111)
12-17 15:11:10.701: E/Tabris(30811): 	at com.eclipsesource.tabris.android.internal.javascript.V8JavaScriptBridge.instantiateV8(V8JavaScriptBridge.java:61)
12-17 15:11:10.701: E/Tabris(30811): 	at com.eclipsesource.tabris.android.internal.javascript.V8JavaScriptBridge.createV8Runtime(V8JavaScriptBridge.java:54)
12-17 15:11:10.701: E/Tabris(30811): 	at com.eclipsesource.tabris.android.internal.javascript.V8JavaScriptBridge.init(V8JavaScriptBridge.java:48)
12-17 15:11:10.701: E/Tabris(30811): 	at com.eclipsesource.tabris.android.internal.javascript.JavaScriptBootStrategy.runJavaScript(JavaScriptBootStrategy.java:119)
12-17 15:11:10.701: E/Tabris(30811): 	at com.eclipsesource.tabris.android.internal.javascript.JavaScriptBootStrategy.run(JavaScriptBootStrategy.java:69)
12-17 15:11:10.701: E/Tabris(30811): 	at com.eclipsesource.tabris.android.internal.TabrisBootstrapper.bootApp(TabrisBootstrapper.java:56)
12-17 15:11:10.701: E/Tabris(30811): 	at com.eclipsesource.tabris.android.internal.TabrisBootstrapper.onPreDraw(TabrisBootstrapper.java:44)
12-17 15:11:10.701: E/Tabris(30811): 	at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1018)
12-17 15:11:10.701: E/Tabris(30811): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2259)
12-17 15:11:10.701: E/Tabris(30811): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1265)
12-17 15:11:10.701: E/Tabris(30811): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6945)
12-17 15:11:10.701: E/Tabris(30811): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:821)
12-17 15:11:10.701: E/Tabris(30811): 	at android.view.Choreographer.doCallbacks(Choreographer.java:606)
12-17 15:11:10.701: E/Tabris(30811): 	at android.view.Choreographer.doFrame(Choreographer.java:576)
12-17 15:11:10.701: E/Tabris(30811): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:807)
12-17 15:11:10.701: E/Tabris(30811): 	at android.os.Handler.handleCallback(Handler.java:739)
12-17 15:11:10.701: E/Tabris(30811): 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-17 15:11:10.701: E/Tabris(30811): 	at android.os.Looper.loop(Looper.java:145)
12-17 15:11:10.701: E/Tabris(30811): 	at android.app.ActivityThread.main(ActivityThread.java:6895)
12-17 15:11:10.701: E/Tabris(30811): 	at java.lang.reflect.Method.invoke(Native Method)
12-17 15:11:10.701: E/Tabris(30811): 	at java.lang.reflect.Method.invoke(Method.java:372)
12-17 15:11:10.701: E/Tabris(30811): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
12-17 15:11:10.701: E/Tabris(30811): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
12-17 15:11:10.701: E/Tabris(30811): Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.sdlportal.sdlmobile3-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sdlportal.sdlmobile3-1/lib/arm64, /vendor/lib64, /system/lib64]]] couldn't find "libj2v8.so"
12-17 15:11:10.701: E/Tabris(30811): 	at java.lang.Runtime.loadLibrary(Runtime.java:367)
12-17 15:11:10.701: E/Tabris(30811): 	at java.lang.System.loadLibrary(System.java:988)
12-17 15:11:10.701: E/Tabris(30811): 	at com.eclipsesource.v8.LibraryLoader.loadLibrary(LibraryLoader.java:43)
12-17 15:11:10.701: E/Tabris(30811): 	at com.eclipsesource.v8.V8.load(V8.java:69)
12-17 15:11:10.701: E/Tabris(30811): 	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:131)
12-17 15:11:10.701: E/Tabris(30811): 	... 24 more
12-17 15:11:10.701: D/Tabris(30811): ERROR J2V8 native library not loaded.
12-17 15:11:10.701: D/PhoneWindow(30811): *FMB* installDecor mIsFloating : true
12-17 15:11:10.701: D/PhoneWindow(30811): *FMB* installDecor flags : 8388610
12-17 15:11:10.751: D/PhoneWindow(30811): *FMB* isFloatingMenuEnabled mFloatingMenuBtn : null
12-17 15:11:10.751: D/PhoneWindow(30811): *FMB* isFloatingMenuEnabled return false
12-17 15:11:10.771: D/SRIB_DCS(30811): log_dcs ThreadedRenderer::initialize entered! 
12-17 15:11:10.771: D/mali_winsys(30811): new_window_surface returns 0x3000,  [1592x1127]-format:1
12-17 15:11:10.811: I/Timeline(30811): Timeline: Activity_idle id: android.os.BinderProxy@a3a0db9 time:253308079
12-17 15:11:10.821: I/Timeline(30811): Timeline: Activity_idle id: android.os.BinderProxy@2eaaec67 time:253308081
```

**Comment by irbull** [comment]
Sorry about this @bFlood. This link may help us. http://stackoverflow.com/questions/30986387/unsatisfiedlinkerror-on-samsung-s6

**Comment by bFlood** [comment]
thanks @irbull this is a pretty big issue for us, there are 50+ testers waiting since their new tablets are not working. We've also heard from two other clients that had the same issue, I'm trying to find out if they were all Samsung devices. So far the issue is confirmed on: Samsung S6, Samsung Galaxy Note5, Samsung Ellipse. I'm fairly certain they all have Android 5.1+ on them but I would need to confirm that

thanks!

**Comment by mpost** [comment]
@bFlood We have successfully run the current Tabris.js 1.5 app from the Play Store on the Samsung Galaxy S6. There were no loading problems for the v8.

Would you allow us to test the build of your app on a Samsung Galaxy S6?

**Comment by bFlood** [comment]
allow us to test - yes, absolutely. thanks

was there a fix or are you just trying to reproduce the error?

**Comment by mpost** [comment]
@bFlood There was no fix. I just installed the app from the store and run it as expected:

![tabris-js-galaxy-s6](https://cloud.githubusercontent.com/assets/73655/11934950/4f9afe6e-a805-11e5-818c-d9a4d48aa87d.png)

**Comment by mpost** [comment]
I run the SDL app. I can confirm that it is not starting and just showing the dialog as you described. We are investigating.

**Comment by mpost** [comment]
We have found the problem... A cordova plugin is contributing 64bit native artifacts (.so files) during the build which creates the 64bit ABI folders. Thereby the 32bit j2v8 libray is not found. We are discussing how to solve the issue.

The external cordova plugin deploys: `libsqlc-native-driver.so`

**Comment by mpost** [comment]
On a side note... The problem is not limited to 64bit samsung devices but applied to all 64 bit devices.

**Comment by bFlood** [comment]
thank you @mpost , let me know if I can help 

fwiw, its running on a Samsung Note 5 with Android 5.0.1 (I believe the Note 5 is 64bit)

**Comment by mpost** [comment]
There are two possible scenarios that we can take now... Either filter out any none 64bit libraries or migrate j2v8 to also support 64bit. The later is of course the better and is also the solution we should strive for.

Given that the 32 bit artifacts of the sql library also work as expected on 32bit, you could right now use a cordova build hook to only include 32 bit native artifacts as outlined in the above [stackoverflow post](http://stackoverflow.com/questions/30986387/unsatisfiedlinkerror-on-samsung-s6):

```xml
android {
    ....
    defaultConfig {
        ....
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
}
```

**Comment by bFlood** [comment]
@mpost thank! its working now on the S6. I'll get a build out for testing on the other devices where it was failing before

I had some issues trying to get the build hook to work but I forked the sqlite plugin and removed the extra 64bit files manually.

**Comment by mpost** [comment]
Good to hear that you could help yourself. In the next release we are going to _enforce_ to only support 32bit libraries. Meaning we will only include abis for "armeabi", "armeabi-v7a" and "x86".

**Comment by mpost** [comment]
We have suppressed the inclusion of any 64 bit libraries in the cordova platform. The sqlite plugin is still able to open a database connection with its 32 bit implementation.
