### ISSUE TITLE
tabris1.5 issue with switch

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#706]
this is a weird one. if a switch is on a CollectionView that is a child of a Tab and you set it's "selection" property to true (false works!) then you get this hard crash on Android. Used to work fine in tabris1.4 if that helps.

``` 
12-16 09:01:00.351: E/AndroidRuntime(7709): FATAL EXCEPTION: main
12-16 09:01:00.351: E/AndroidRuntime(7709): Process: com.sdlportal.sdlmobile3, PID: 7709
12-16 09:01:00.351: E/AndroidRuntime(7709): java.lang.NullPointerException: Attempt to write to field 'int android.support.v7.widget.RecyclerView$ViewHolder.mItemViewType' on a null object reference
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5229)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4453)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4363)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1961)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1370)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1333)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:562)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2900)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3071)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.View.layout(View.java:16701)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:584)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.View.layout(View.java:16701)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.View.layout(View.java:16701)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.View.layout(View.java:16701)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.View.layout(View.java:16701)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.View.layout(View.java:16701)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.View.layout(View.java:16701)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.View.layout(View.java:16701)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.View.layout(View.java:16701)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.View.layout(View.java:16701)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.View.layout(View.java:16701)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.View.layout(View.java:16701)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.View.layout(View.java:16701)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2344)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2057)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1216)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6678)
12-16 09:01:00.351: E/AndroidRuntime(7709): 	at android.view.Choreographer$CallbackRecord.run(
```

**Comment by bFlood** [comment]
I switched to a CheckBox and it works fine so no rush on this

cheers

**Comment by mpost** [comment]
@bFlood Thanks for the heads-up. We will investigate. Could you provide a snippet for the scenario you describe?

**Comment by mpost** [comment]
We have tried to reproduce the issue with the following snippet but found it to perform correctly:

```js
var people = [1,2,3,4];

var page = tabris.create("Page", {
  title: "TabFolder",
  topLevel: true
});

var tabFolder = tabris.create("TabFolder", {
  layoutData: {left: 0, top: 0, right: 0, bottom: 0},
  paging: true // enables swiping. To still be able to open the developer console in iOS, swipe from the bottom right.
}).appendTo(page);

var createTab = function(title, image) {
  var tab = tabris.create("Tab", {

    image: {src: image, scale: 2},
    background: "white"
  }).appendTo(tabFolder);
  tabris.create("CollectionView", {
    layoutData: {left: 0, top: 0, right: 0, bottom: 0},
    items: people,
    itemHeight: 48,
    initializeCell: function(cell) {
      tabris.create("Switch", {
        layoutData: {top: 16, centerX: 0},
        selection: true
      }).appendTo(cell);
    }
  }).appendTo(tab);
  return tab;
};

createTab("Cart", "images/cart.png");
createTab("Pay", "images/card.png");
createTab("Statistic", "images/chart.png");

page.open();
```

Do you have any more insights?

**Comment by bFlood** [comment]
that code works for me too, I'm not sure what is happening in my other example (but it is still reproducible on the latest build). I'll see if I can isolate the issue more and get back to you

**Comment by mpost** [comment]
@bFlood Any more insights on this issue?

**Comment by bFlood** [comment]
hi @mpost - yes, actually I think I have figured out what was happening (at least in my case). I had code in the Switch "select" event that would close the page. Setting the switch "selection" property to true on load would cause this event to fire on Android (fwiw, I thought this what "change:selection" was for) . I guess due to animations etc not completing yet, this would cause the hard crash above. when I introduced a slight delay in the "select" handler, the page would open and then close without the crash

so, the issue seems to be the "select" event being called when you set the "selection" property to true on android. you can guard against this with a simple loading flag or just switch to a CheckBox (like I did)

cheers, sorry for not posting this info before. I'm going to leave it open since I do think this might be a bug

**Comment by mpost** [comment]
@bFlood Thanks for the additional feedback. That should help us to narrow down the problem.

**Comment by mpost** [comment]
@bFlood We have fixed the `select` event bug on Android. the event is now only fired on user initiated selection. Could you please check that the problem you are describing has been resolved?
