### ISSUE TITLE
minor android crash issue

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#708]
I get this error infrequently but it usually happens when you click the back button on a page where tabs are present

``` 
12-17 11:04:36.619: E/AndroidRuntime(4568): FATAL EXCEPTION: main
12-17 11:04:36.619: E/AndroidRuntime(4568): Process: com.sdlportal.sdlmobile3, PID: 4568
12-17 11:04:36.619: E/AndroidRuntime(4568): java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getLeft()' on a null object reference
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.support.design.widget.TabLayout$SlidingTabStrip.animateIndicatorToPosition(TabLayout.java:1599)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.support.design.widget.TabLayout$SlidingTabStrip.onLayout(TabLayout.java:1554)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.View.layout(View.java:16701)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.HorizontalScrollView.onLayout(HorizontalScrollView.java:2033)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.View.layout(View.java:16701)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.View.layout(View.java:16701)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.View.layout(View.java:16701)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.View.layout(View.java:16701)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.View.layout(View.java:16701)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1077)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.View.layout(View.java:16701)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.View.layout(View.java:16701)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.View.layout(View.java:16701)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1043)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.View.layout(View.java:16701)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.View.layout(View.java:16701)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.View.layout(View.java:16701)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.View.layout(View.java:16701)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.View.layout(View.java:16701)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.View.layout(View.java:16701)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.ViewGroup.layout(ViewGroup.java:5328)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2344)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2057)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1216)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6678)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
12-17 11:04:36.619: E/AndroidRuntime(4568): 	at android.vie
```

**Comment by bFlood** [comment]
I think I spoke too soon, I'm getting these all the time now in tabris1.5

click the back button on a page with Tabs and paging:true

**Comment by bFlood** [comment]
after further testing, paging:true is not part of the problem, it still crashed with this turned to false

this is a pretty big issue, it crashes a lot just click the back button (navbar or hardware back button)

**Comment by jonek** [comment]
@bFlood Here is is a simple snippet that implements you described scenario. I can not reproduce the problem you describe. Please check with his snippet and modify it to reproduce your problem. Thanks.
```javascript
var pageCount = 0;

createPage("Initial Page", true);

function createTab(title, tabFolder) {
  var tab = tabris.create("Tab", {
    title: title, // converted to upper-case on Android
  }).appendTo(tabFolder);
  tabris.create("TextView", {
    layoutData: {centerX: 0, centerY: 0},
    text: "Content of Tab " + title
  }).appendTo(tab);
}

function createPage(title, topLevel) {
  var page = tabris.create("Page", {
    title: title,
    topLevel: topLevel
  }).open();

  var button = tabris.create("Button", {
    layoutData: {left: 10, top: 10, right: 10},
    text: "Create another page"
  }).on("select", function() {
    createPage("Page " + (++pageCount), false);
  }).appendTo(page);
  var tabFolder = tabris.create("TabFolder", {
    layoutData: {left: 0, top: [button, 30], right: 0, bottom: 0},
    paging: true // enables swiping. To still be able to open the developer console in iOS, swipe from the bottom right.
  }).appendTo(page);
  createTab("Foo Tab", tabFolder);
  createTab("Bar Tab", tabFolder);
}
```

**Comment by jonek** [comment]
Ok, I can now reproduce your problem. Steps to reproduce:
1. put above snippet in scratchpad
2. open in latest Tabris.js 1.5.0 developer app
3. start via "My Scratchpad"
4. click "Create another page"
5. swipe to second tab "BAR TAB"
6. press back button or press back arrow in toolbar
7. crash

The problem does not occur when I just create new pages and navigate back without swiping or switching to a second tab on any page.

**Comment by bFlood** [comment]
thanks @jonek I can confirm you must move to another tab before the crash happens

**Comment by mpost** [comment]
@bFlood We have fixed the issue in the android client. It is already available in the nightly builds. We will also publish a 1.5.1 update that includes the fix. Thanks for reporting.

**Comment by bFlood** [comment]
confirmed, thanks!
