### ISSUE TITLE
Support local notifications

### ISSUE THREAD

**Issue by cookieguru** [eclipsesource/tabris-js#743]
There are many [Cordova plugins showing notifications](https://cordova.apache.org/plugins/?q=notification), and most are designed for receiving push notifications.  I've found only one is designed for locally-generated notifications: [cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications).  This also appears to be the only plugin that supports ongoing notifications.

When adding the plugin (version 1.0.0) to `config.xml` the build fails at the following step:

```plain
...
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugResources
:generateDebugSources
:compileDebugJava/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:564: error: cannot find symbol
                    webView.evaluateJavascript(js, null);
                           ^
  symbol:   method evaluateJavascript(String,)
  location: variable webView of type CordovaWebView
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/src/de/appplant/cordova/plugin/localnotification/LocalNotification.java:561: error: cannot find symbol
        webView.post(new Runnable(){
               ^
  symbol:   method post()
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/src/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:packageAllDebugClassesForMultiDex FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: android/support/annotation/AttrRes.class
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 1 mins 3.721 secs
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/cordova/build: Command failed with exit code 8
You may not have the required environment or OS to build this project
Error: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/cordova/build: Command failed with exit code 8
    at ChildProcess.whenDone (/home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
Warning: Command failed: Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/src/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: android/support/annotation/AttrRes.class
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build.gradle,-Dorg.gradle.daemon=true
Error: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/cordova/build: Command failed with exit code 8
    at ChildProcess.whenDone (/home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
 Use --force to continue.
Aborted due to warnings.
travis_time:end:050b0570:start=1453667958600688729,finish=1453668037390511551,duration=78789822822

The command "grunt build deploy" exited with 6.
Done. Your build exited with 1.
```

---

There's also [cordova-plugin-local-notifications-pgb](https://github.com/VitaliiBlagodir/cordova-plugin-local-notifications-pgb) which fixes some of the issues this plugin has with PhoneGap build, but it fails with the following:

```plain
...
:generateDebugAssets UP-TO-DATE
:mergeDebugAssets
:generateDebugResValues
:generateDebugResources
:mergeDebugResources
:processDebugResources
:generateDebugSources
:compileDebugJavaNote: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/src/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:packageAllDebugClassesForMultiDex FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: android/support/annotation/AttrRes.class
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 1 mins 3.721 secs
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build.gradle,-Dorg.gradle.daemon=true
ERROR building one of the platforms: Error: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/cordova/build: Command failed with exit code 8
You may not have the required environment or OS to build this project
Error: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/cordova/build: Command failed with exit code 8
    at ChildProcess.whenDone (/home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
Warning: Command failed: Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/src/org/apache/cordova/file/AssetFilesystem.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':packageAllDebugClassesForMultiDex'.
> java.util.zip.ZipException: duplicate entry: android/support/annotation/AttrRes.class
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/cordova/node_modules/q/q.js:126
                    throw e;
                          ^
Error code 1 for command: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/gradlew with args: cdvBuildDebug,-b,/home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/build.gradle,-Dorg.gradle.daemon=true
Error: /home/travis/build/eclipsesource/tabris-js-build-template/build/platforms/android/cordova/build: Command failed with exit code 8
    at ChildProcess.whenDone (/home/travis/.nvm/v0.10.36/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
 Use --force to continue.
Aborted due to warnings.
travis_time:end:050b0570:start=1453667958600688729,finish=1453668037390511551,duration=78789822822

The command "grunt build deploy" exited with 6.
Done. Your build exited with 1.
```

**Comment by mpost** [comment]
Apparently there is a problem with this plugin on Cordova 5 https://github.com/katzer/cordova-plugin-local-notifications/issues/426

Do you build against tabris.js nightly? We have migrated to Cordova 5.0.0 for the upcoming Tabris.js 1.6 release.

**Comment by cookieguru** [comment]
@mpost I had been building against 1.5

**Comment by mpost** [comment]
I would like to think that the error is on their side. Could you try against Tabris.js nightly although that shouldn't have too much impact.

**Comment by cookieguru** [comment]
Finally got a passing build.  Will play around with this tomorrow to see if everything is working.

In case anyone else is interested:
```xml
<plugin name="https://github.com/C895/cordova-plugin-local-notifications.git" />
```

**Comment by cookieguru** [comment]
Also, this built successfully against both 1.5.0 and nightly

**Comment by mpost** [comment]
Good to hear. :)

**Comment by cookieguru** [comment]
Fails on app launch.
```plain
TypeError: Cannot redefine property: device
TypeError: Cannot redefine property: device
    at Function.defineProperty (native)
    at Object.utils.defineGetterSetter (./cordova.js:1759:16)
    at clobber (./cordova.js:531:15)
    at Object.assignOrWrapInDeprecateGetter (./cordova.js:546:9)
    at Object.exports.mapModules (./cordova.js:1465:21)
    at ./cordova.js:1255:18
    at f (./cordova.js:693:33)
    at Channel.fire (./cordova.js:821:23)
    at ./cordova.js:1247:32
    at onScriptLoadingComplete (./cordova.js:1667:5)
deviceready has not fired after 5 seconds.
Channel not fired: onCordovaReady
Channel not fired: onCordovaInfoReady
```

**Comment by mpost** [comment]
Okay, we would have to investigate what kind of environment the plugin requires.

**Comment by elfazzo** [comment]
Hi, we are currently assessing whether to use TabrisJS instead of just cordova for our next app build. We will require the use of local notifications. Has this issue progressed any further as I was getting similar issues when trying to use this cordova plugin. 

Or are there any other ways of triggering local notifications using TabrisJS?

**Comment by ralfstx** [comment]
I've opened #785 for the problem with the cordova device plugin. Chances are that the local-notifications plugin works when this issue is fixed.

**Comment by ralfstx** [comment]
@mpost Could you try again?

**Comment by cookieguru** [comment]
@ralfstx When will #785 be in the Tabris.js nightly build?  I just built an app and see the same error.

**Comment by ralfstx** [comment]
@cookieguru the nightly build should pick up the change. Please try again tomorrow.

**Comment by cookieguru** [comment]
Now seeing this error on startup:
```
Could not load tabris module: TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
    at d.extend._nativeGet (./node_modules/tabris/tabris.min.js:32:16343)
    at f (./node_modules/tabris/tabris.min.js:32:4515)
    at tabris.Properties.get (./node_modules/tabris/tabris.min.js:32:13211)
    at Function.tabris._publishDeviceProperties (./node_modules/tabris/tabris.min.js:33:9376)
    at ./node_modules/tabris/tabris.min.js:33:9465
    at ./node_modules/tabris/tabris.min.js:33:9498
    at ./node_modules/tabris/tabris.min.js:34:15245
    at Object.defineProperty.get (<anonymous>:1:1401)
    at Object.i.require (<anonymous>:1:1570)
    at Object.tabris._start (<anonymous>:1:2695)
```
In this case `_nativeGet` is referring to [`Proxy`'s `_nativeGet`](https://github.com/eclipsesource/tabris-js/blob/748f05b43f17a5cc1701b8039ebd5f5c6e346065/src/tabris/Proxy.js#L98).

**Comment by mpost** [comment]
I can confirm the error reported by @cookieguru

**Comment by ralfstx** [comment]
May bad, sorry! Working on a fix right now.

**Comment by mpost** [comment]
@cookieguru @elfazzo In general we can confirm that the plugin works. We are still having some problems with the device object that is required internally. We are working currently working on a fix.

Here you can see the plugin working, which we will soon enable for everybody:

![screenshot_20160217-152504](https://cloud.githubusercontent.com/assets/73655/13112366/a4939644-d58a-11e5-8460-ea0046854f68.png)

**Comment by mpost** [comment]
@cookieguru @elfazzo We have remedied the problem with the device in the latest nightly. You should now be able to use the [notification plugin](https://github.com/katzer/cordova-plugin-local-notifications) as advertised.

Please let us know if you have any more problems.

**Comment by elfazzo** [comment]
@mpost Thanks, will be trying this in the next few days. Will let you know if there are any issues.

**Comment by cookieguru** [comment]
@mpost I still see [this error](https://github.com/eclipsesource/tabris-js/issues/743#issuecomment-175798804) on launch when building with nightly using [de.appplant.cordova.plugin.local-notification](https://www.npmjs.com/package/de.appplant.cordova.plugin.local-notification)@0.8.4.

**Comment by mpost** [comment]
@cookieguru this error is two steps back... are you certain you build against nightly?

**Comment by mpost** [comment]
@cookieguru I can confirm your reported error. Apparently the build service is not yet in sync with our changes. I'll report when it is working properly.

**Comment by mpost** [comment]
@cookieguru The build service has configuration problem when building a debug build with nightly. It does not make use of the nightly builds. In fact it builds against what is given in your `package.json` `dependencies`. Therefore you can currently enforce to use `nightly` by specifying it explicitly in the `package.json`: 

```js
  "dependencies": {
    "tabris": "https://tabrisjs.com/downloads/nightly/tabris.tgz"
  }
```

**Comment by cookieguru** [comment]
Using the above instructions to build against nightly with [de.appplant.cordova.plugin.local-notification](https://www.npmjs.com/package/de.appplant.cordova.plugin.local-notification)@0.8.4 works great.  Have only tested Android so far.

Using [this omnibus script](http://pastebin.com/raw/m2HyZcsJ) everything works except loading icons from remote URLs.  Did not test locally loaded icons, however I did notice that the app locally caches the remote icons.

**Comment by jumpjack** [comment]
any working "hello world" example showing how to use cordova plugins, and specifically notifications plugin?
