### ISSUE TITLE
Best Cordova Background Service for Tabris

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#831]
Want to give notifcation when new items (feeds) arrive when app is not in view.

**Comment by iteearmah** [comment]
I'm using <plugin name="https://github.com/katzer/cordova-plugin-background-mode.git" />
It seem works but I get the following when the app goes into background mode. 
`TypeError: a.apply is not a function
TypeError: a.apply is not a function
    at .<anonymous> (./node_modules/tabris/tabris.min.js:33:3079)
    at tabris.Events._callAll (./node_modules/tabris/tabris.min.js:32:9419)
    at tabris.Events.trigger (./node_modules/tabris/tabris.min.js:32:9241)
    at d.extend._trigger (./node_modules/tabris/tabris.min.js:32:16132)
    at Function.window.tabris.a.exports.d.extend._notify (./node_modules/tabris/tabris.min.js:32:6078)
TypeError: a.apply is not a function
TypeError: a.apply is not a function
    at .<anonymous> (./node_modules/tabris/tabris.min.js:33:3079)
    at tabris.Events._callAll (./node_modules/tabris/tabris.min.js:32:9419)
    at tabris.Events.trigger (./node_modules/tabris/tabris.min.js:32:9241)
    at d.extend._trigger (./node_modules/tabris/tabris.min.js:32:16132)
    at Function.window.tabris.a.exports.d.extend._notify (./node_modules/tabris/tabris.min.js:32:6078)`

**Comment by camstuart** [comment]
Any further luck with this? I was just exploring how to do exactly that and came across the same plugin.

Unless a better option is available?

**Comment by mpost** [comment]
The plugin states _The plugin focuses on enterprise-only distribution and may not compliant with all public store vendors_. So it would not be my first choice as it most likely violates iOS app store policies and would be considered an ill behaving Android app.

Going forward Tabris should support to execute js code independent of the main tread/ui thread. Until than it is advised to use cloud messaging to interact with the app while in the background.

**Comment by ralfstx** [comment]
This question appears to be answered. Please re-open if you need further help.
