### ISSUE TITLE
TypeError: a.apply is not a function for Cordova Background Plug-in

### ISSUE THREAD

**Issue by iteearmah** [eclipsesource/tabris-js#832]
I'm using the plugin
`<plugin name="https://github.com/katzer/cordova-plugin-background-mode.git" />`

the following is the code in the mainapp.js file

```

cordova.plugins.backgroundMode.enable();
cordova.plugins.backgroundMode.onactivate = function () {
        setTimeout(function () {
            // Modify the currently displayed notification
            cordova.plugins.backgroundMode.configure({
                text:'Running in background for more than 5s now.'
            });
        }, 10000);
    }

```

It seem works but I get the following when the app goes into background mode. 

```

TypeError: a.apply is not a function
TypeError: a.apply is not a function
    at .<anonymous> (./node_modules/tabris/tabris.min.js:33:3079)
    at tabris.Events._callAll (./node_modules/tabris/tabris.min.js:32:9419)
    at tabris.Events.trigger (./node_modules/tabris/tabris.min.js:32:9241)
    at d.extend._trigger (./node_modules/tabris/tabris.min.js:32:16132)
    at Function.window.tabris.a.exports.d.extend._notify (./node_modules/tabris/tabris.min.js:32:6078)
TypeError: a.apply is not a function
TypeError: a.apply is not a function
    at .<anonymous> (./node_modules/tabris/tabris.min.js:33:3079)
    at tabris.Events._callAll (./node_modules/tabris/tabris.min.js:32:9419)
    at tabris.Events.trigger (./node_modules/tabris/tabris.min.js:32:9241)
    at d.extend._trigger (./node_modules/tabris/tabris.min.js:32:16132)
    at Function.window.tabris.a.exports.d.extend._notify (./node_modules/tabris/tabris.min.js:32:6078)

```

**Comment by ralfstx** [comment]
To interpret the stacktrace, it would help to know the exact tabris version.

**Comment by iteearmah** [comment]
version 1.7.0

**Comment by ralfstx** [comment]
The error comes from [this line](https://github.com/eclipsesource/tabris-js/blob/v1.7.0/src/tabris/WindowTimers.js#L27). It seems that you (or the cordova plugin) calls `setTimeout()` either without parameters or with the first parameter not being a function.

**Comment by iteearmah** [comment]
can I get the update in the nightly build?

**Comment by mpost** [comment]
@iteearmah The change is in the nightly build.

**Comment by iteearmah** [comment]
below is my dependencies in my package.json, how do I make it to use the nightly build?
I created a release apk and selected the nightly build in the dropdown but the error still comes.
````
"dependencies": {
    "tabris": "^1.7.0"
  }
````

**Comment by mpost** [comment]
You point to the nightly url:

```js
  "dependencies": {
    "tabris": "https://tabrisjs.com/downloads/nightly/tabris.tgz"
  }
```

**Comment by mpost** [comment]
With tabris 1.10 we added `foreground` and `background` events on `tabris.app`. Therefore closing this issue. Feel free to reopen if required.
