### ISSUE TITLE
NoClassDefFoundError - custom plugin

### ISSUE THREAD

**Issue by bFlood** [eclipsesource/tabris-js#894]
I have a custom plugin that contains a 3rd party jar file and related *.so files for x86 and armeabi-v7a. I'm using the tabris build service and everything compiles correctly (and if I remove the jar or either of the so files, as expected, it will not compile)

here's how they are added in the plugin.xml file:
``` xml
        <source-file src="src/android/libs/arcgis-android-api.jar" target-dir="libs"/>

        <source-file src="src/android/libs/x86/libruntimecore_java.so" target-dir="libs/x86"/>
        <source-file src="src/android/libs/armeabi-v7a/libruntimecore_java.so" target-dir="libs/armeabi-v7a"/>
```

that said, when I run the app on a device, I get the following error:
``` log
06-17 15:59:19.741: E/AndroidRuntime(5333): FATAL EXCEPTION: main
06-17 15:59:19.741: E/AndroidRuntime(5333): Process: com.sdlportal.sdlmobile3, PID: 5333
06-17 15:59:19.741: E/AndroidRuntime(5333): java.lang.NoClassDefFoundError: Failed resolution of: Lcom/esri/arcgisruntime/R$drawable;
06-17 15:59:19.741: E/AndroidRuntime(5333): 	at com.esri.arcgisruntime.mapping.view.MapView.a(SourceFile:888)
06-17 15:59:19.741: E/AndroidRuntime(5333): 	at com.esri.arcgisruntime.mapping.view.MapView.<init>(SourceFile:211)
06-17 15:59:19.741: E/AndroidRuntime(5333): 	at com.esri.arcgisruntime.mapping.view.MapView.<init>(SourceFile:221)
06-17 15:59:19.741: E/AndroidRuntime(5333): 	at com.spatialdatalogic.tabris.gmaps.MapHolderView.onMapReady(MapHolderView.java:175)
06-17 15:59:19.741: E/AndroidRuntime(5333): 	at com.google.android.gms.maps.MapFragment$zza$1.zza(Unknown Source)
06-17 15:59:19.741: E/AndroidRuntime(5333): 	at com.google.android.gms.maps.internal.zzl$zza.onTransact(Unknown Source)
06-17 15:59:19.741: E/AndroidRuntime(5333): 	at android.os.Binder.transact(Binder.java:387)
06-17 15:59:19.741: E/AndroidRuntime(5333): 	at wv.a(:com.google.android.gms.DynamiteModulesB:82)
06-17 15:59:19.741: E/AndroidRuntime(5333): 	at maps.ag.t$5.run(Unknown Source)
06-17 15:59:19.741: E/AndroidRuntime(5333): 	at android.os.Handler.handleCallback(Handler.java:739)
06-17 15:59:19.741: E/AndroidRuntime(5333): 	at android.os.Handler.dispatchMessage(Handler.java:95)
06-17 15:59:19.741: E/AndroidRuntime(5333): 	at android.os.Looper.loop(Looper.java:158)
06-17 15:59:19.741: E/AndroidRuntime(5333): 	at android.app.ActivityThread.main(ActivityThread.java:7229)
06-17 15:59:19.741: E/AndroidRuntime(5333): 	at java.lang.reflect.Method.invoke(Native Method)
06-17 15:59:19.741: E/AndroidRuntime(5333): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
06-17 15:59:19.741: E/AndroidRuntime(5333): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
06-17 15:59:19.741: E/AndroidRuntime(5333): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.esri.arcgisruntime.R$drawable" on path: DexPathList[[zip file "/data/app/com.sdlportal.sdlmobile3-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sdlportal.sdlmobile3-1/lib/arm, /data/app/com.sdlportal.sdlmobile3-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
06-17 15:59:19.741: E/AndroidRuntime(5333): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
06-17 15:59:19.741: E/AndroidRuntime(5333): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
06-17 15:59:19.741: E/AndroidRuntime(5333): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
06-17 15:59:19.741: E/AndroidRuntime(5333): 	... 16 more
06-17 15:59:19.741: E/AndroidRuntime(5333): 	Suppressed: java.lang.ClassNotFoundException: com.esri.arcgisruntime.R$drawable
06-17 15:59:19.741: E/AndroidRuntime(5333): 		at java.lang.Class.classForName(Native Method)
06-17 15:59:19.741: E/AndroidRuntime(5333): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
06-17 15:59:19.741: E/AndroidRuntime(5333): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
06-17 15:59:19.741: E/AndroidRuntime(5333): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
06-17 15:59:19.741: E/AndroidRuntime(5333): 		... 17 more
06-17 15:59:19.741: E/AndroidRuntime(5333): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

```

does anyone have any thoughts on why this would be happening? It compiled correctly so its odd that it can't find the class definitions at runtime???

**Comment by mpost** [comment]
that might be related to the drawable resource id resolution that is not supported inside a cordova plugin. cordova plugins are not "proper" gradle modules and have to resolve their ressources "as strings".

**Comment by bFlood** [comment]
thank you @mpost, if this is the case can you think of a workaround?

**Comment by mpost** [comment]
bundling as .aar should help.

**Comment by bFlood** [comment]
this seemed to work, thanks for the tip @mpost !

**Comment by bFlood** [comment]
ok, I think I spoke too soon. I'm still getting NoClassDefFoundError at runtime using the aar file

can you give me some feedback on the best way to include an aar file in the tabris build server process? I have a pom file as well that includes two external dependencies the aar file needs 
thanks

**Comment by mpost** [comment]
To recap... you are getting the same exception as above or the resource class not resolved? I am not 100 sure how hat is handled when bundled as an .aar. In case of a jar the resources wouldn't be resolvable because the generated resource ids are not available in the jar. Could it be the same with the .aar?

**Comment by bFlood** [comment]
no, it was a different NoClassDefFoundError this time, not the resource class error above. It did not cause a fatal crash but it obviously prevented the app from working

that said, I was able to copy how their sample app in Android Studio gradle file was setup and then used their bintray dependency instead of the local aar file. that worked!

so, I am up and running now but if anyone comes across this issue again, I was not able to get a local aar file to work at runtime (compiled ok). This is probably because the the aar in question was pretty complex and used jni and native files internally but I really don't know for sure
